/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.sacyl.caza.farmacia.vista;

/**
 *
 * @author enrique
 */
public class PanelMaterialEnvasar extends javax.swing.JPanel {

    /**
     * 
     * @param add true para mostrar los botones de añadir/cancelar un material a un medicamento
     */
    public PanelMaterialEnvasar(boolean add) {
        initComponents();
        jButtonAddMaterialEnvasar.setVisible(add);
        jButtonCancelarAddMaterialEnvasar.setVisible(add);
        jButtonAceptarMaterialEnvasar.setVisible(false);
        jButtonCancelarMaterialEnvasar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaterialEnvasado = new javax.swing.JPanel();
        jToolBarMaterialEnvasar = new javax.swing.JToolBar();
        jButtonPrimeroMaterialEnvasar = new javax.swing.JButton();
        jButtonAtrasMaterialEnvasar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabelPosicionMaterialEnvasar = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteMaterialEnvasar = new javax.swing.JButton();
        jButtonUltimoMaterialEnvasar = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButtonNuevoMaterialEnvasar = new javax.swing.JButton();
        jButtonModificarMaterialEnvasar = new javax.swing.JButton();
        jButtonEliminarMaterialEnvasar = new javax.swing.JButton();
        jPanelProductosBuscar2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxBuscarMaterialEnvasar = new javax.swing.JComboBox();
        jTextFieldBuscarMaterialEnvasar = new javax.swing.JTextField();
        jButtonBuscarMaterialEnvasar = new javax.swing.JButton();
        jButtonQuitarBuscarMaterialEnvasar = new javax.swing.JButton();
        jPanelListaMaterialEnvasar = new javax.swing.JPanel();
        jScrollPaneListaMaterial = new javax.swing.JScrollPane();
        jListMaterialEnvasar = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jPanelEdicionDatosMaterialEnvasar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonCancelarMaterialEnvasar = new javax.swing.JButton();
        jButtonAceptarMaterialEnvasar = new javax.swing.JButton();
        jLabelIdMaterialEnvasar = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaMaterialEnvasar = new javax.swing.JTextArea();
        jCheckBoxTenemosMaterialEnvasar = new javax.swing.JCheckBox();
        jButtonAddMaterialEnvasar = new javax.swing.JButton();
        jButtonCancelarAddMaterialEnvasar = new javax.swing.JButton();

        jPanelMaterialEnvasado.setBackground(new java.awt.Color(255, 255, 255));

        jToolBarMaterialEnvasar.setBackground(new java.awt.Color(237, 255, 255));
        jToolBarMaterialEnvasar.setFloatable(false);
        jToolBarMaterialEnvasar.setRollover(true);

        jButtonPrimeroMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroMaterialEnvasar.setToolTipText("Se coloca en el primer material para envasar");
        jButtonPrimeroMaterialEnvasar.setEnabled(false);
        jButtonPrimeroMaterialEnvasar.setFocusable(false);
        jButtonPrimeroMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonPrimeroMaterialEnvasar);

        jButtonAtrasMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasMaterialEnvasar.setToolTipText("Se coloca en el material para envasar anterior");
        jButtonAtrasMaterialEnvasar.setEnabled(false);
        jButtonAtrasMaterialEnvasar.setFocusable(false);
        jButtonAtrasMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonAtrasMaterialEnvasar);
        jToolBarMaterialEnvasar.add(jSeparator8);

        jLabelPosicionMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionMaterialEnvasar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionMaterialEnvasar.setText("Maquinaria 200 de 300");
        jLabelPosicionMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarMaterialEnvasar.add(jLabelPosicionMaterialEnvasar);
        jToolBarMaterialEnvasar.add(jSeparator9);

        jButtonSiguienteMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteMaterialEnvasar.setToolTipText("Se coloca en el material para envasar siguiente");
        jButtonSiguienteMaterialEnvasar.setFocusable(false);
        jButtonSiguienteMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonSiguienteMaterialEnvasar);

        jButtonUltimoMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoMaterialEnvasar.setToolTipText("Se coloca en el último material para envasar");
        jButtonUltimoMaterialEnvasar.setFocusable(false);
        jButtonUltimoMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonUltimoMaterialEnvasar);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator10.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarMaterialEnvasar.add(jSeparator10);

        jButtonNuevoMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoAgregar.png"))); // NOI18N
        jButtonNuevoMaterialEnvasar.setToolTipText("Crea un nuevo material para envasar");
        jButtonNuevoMaterialEnvasar.setFocusable(false);
        jButtonNuevoMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonNuevoMaterialEnvasar);

        jButtonModificarMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoEditar.png"))); // NOI18N
        jButtonModificarMaterialEnvasar.setToolTipText("Permite modificar el material para envasar actual");
        jButtonModificarMaterialEnvasar.setFocusable(false);
        jButtonModificarMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonModificarMaterialEnvasar);

        jButtonEliminarMaterialEnvasar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoBorrar.png"))); // NOI18N
        jButtonEliminarMaterialEnvasar.setToolTipText("Elimina el material para envasar actual");
        jButtonEliminarMaterialEnvasar.setFocusable(false);
        jButtonEliminarMaterialEnvasar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarMaterialEnvasar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonEliminarMaterialEnvasar);

        jPanelProductosBuscar2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Buscar por:");

        jComboBoxBuscarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarMaterialEnvasar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Material de envasar", "Tenemos" }));
        jComboBoxBuscarMaterialEnvasar.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarMaterialEnvasar.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarMaterialEnvasar.setMnemonic('B');
        jButtonBuscarMaterialEnvasar.setText("Buscar");
        jButtonBuscarMaterialEnvasar.setToolTipText("Buscar productos que coincidan con los criterios elegidos");

        jButtonQuitarBuscarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarMaterialEnvasar.setMnemonic('Q');
        jButtonQuitarBuscarMaterialEnvasar.setText("Quitar búsqueda");
        jButtonQuitarBuscarMaterialEnvasar.setToolTipText("Volver a mostrar todos los datos");

        javax.swing.GroupLayout jPanelProductosBuscar2Layout = new javax.swing.GroupLayout(jPanelProductosBuscar2);
        jPanelProductosBuscar2.setLayout(jPanelProductosBuscar2Layout);
        jPanelProductosBuscar2Layout.setHorizontalGroup(
            jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarMaterialEnvasar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscar2Layout.setVerticalGroup(
            jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarMaterialEnvasar)
                    .addComponent(jButtonQuitarBuscarMaterialEnvasar))
                .addContainerGap())
        );

        jPanelListaMaterialEnvasar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaMaterialEnvasar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true), "Lista de materiales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jListMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jListMaterialEnvasar.setToolTipText("Si se selecciona un material para envasar se verán sus datos a la derecha");
        jScrollPaneListaMaterial.setViewportView(jListMaterialEnvasar);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("¿Tenemos?- Material");

        javax.swing.GroupLayout jPanelListaMaterialEnvasarLayout = new javax.swing.GroupLayout(jPanelListaMaterialEnvasar);
        jPanelListaMaterialEnvasar.setLayout(jPanelListaMaterialEnvasarLayout);
        jPanelListaMaterialEnvasarLayout.setHorizontalGroup(
            jPanelListaMaterialEnvasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaMaterialEnvasarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaMaterialEnvasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelListaMaterialEnvasarLayout.setVerticalGroup(
            jPanelListaMaterialEnvasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaMaterialEnvasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaMaterial)
                .addContainerGap())
        );

        jPanelEdicionDatosMaterialEnvasar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosMaterialEnvasar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Edición de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosMaterialEnvasar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("ID:");
        jPanelEdicionDatosMaterialEnvasar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Material envasar:");
        jPanelEdicionDatosMaterialEnvasar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Tenemos:");
        jPanelEdicionDatosMaterialEnvasar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButtonCancelarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarMaterialEnvasar.setMnemonic('C');
        jButtonCancelarMaterialEnvasar.setText("Cancelar");
        jPanelEdicionDatosMaterialEnvasar.add(jButtonCancelarMaterialEnvasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jButtonAceptarMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAceptarMaterialEnvasar.setMnemonic('A');
        jButtonAceptarMaterialEnvasar.setText("Aceptar");
        jPanelEdicionDatosMaterialEnvasar.add(jButtonAceptarMaterialEnvasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabelIdMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIdMaterialEnvasar.setText("44");
        jPanelEdicionDatosMaterialEnvasar.add(jLabelIdMaterialEnvasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, -1));

        jTextAreaMaterialEnvasar.setEditable(false);
        jTextAreaMaterialEnvasar.setColumns(20);
        jTextAreaMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaMaterialEnvasar.setLineWrap(true);
        jTextAreaMaterialEnvasar.setRows(5);
        jTextAreaMaterialEnvasar.setToolTipText("Nombre del material para envasar");
        jScrollPane7.setViewportView(jTextAreaMaterialEnvasar);

        jPanelEdicionDatosMaterialEnvasar.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 60));

        jCheckBoxTenemosMaterialEnvasar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTenemosMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxTenemosMaterialEnvasar.setText("Sí");
        jCheckBoxTenemosMaterialEnvasar.setEnabled(false);
        jPanelEdicionDatosMaterialEnvasar.add(jCheckBoxTenemosMaterialEnvasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 255, -1, -1));

        jButtonAddMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAddMaterialEnvasar.setText("Añadir");

        jButtonCancelarAddMaterialEnvasar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarAddMaterialEnvasar.setText("Cancelar");

        javax.swing.GroupLayout jPanelMaterialEnvasadoLayout = new javax.swing.GroupLayout(jPanelMaterialEnvasado);
        jPanelMaterialEnvasado.setLayout(jPanelMaterialEnvasadoLayout);
        jPanelMaterialEnvasadoLayout.setHorizontalGroup(
            jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMaterialEnvasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMaterialEnvasadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductosBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMaterialEnvasadoLayout.createSequentialGroup()
                        .addComponent(jPanelListaMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMaterialEnvasadoLayout.createSequentialGroup()
                                .addComponent(jButtonAddMaterialEnvasar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelarAddMaterialEnvasar))
                            .addComponent(jPanelEdicionDatosMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelMaterialEnvasadoLayout.setVerticalGroup(
            jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialEnvasadoLayout.createSequentialGroup()
                .addComponent(jToolBarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelProductosBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEdicionDatosMaterialEnvasar, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPanelListaMaterialEnvasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanelMaterialEnvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMaterialEnvasar)
                    .addComponent(jButtonCancelarAddMaterialEnvasar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMaterialEnvasado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelMaterialEnvasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarMaterialEnvasar;
    public javax.swing.JButton jButtonAddMaterialEnvasar;
    public javax.swing.JButton jButtonAtrasMaterialEnvasar;
    public javax.swing.JButton jButtonBuscarMaterialEnvasar;
    public javax.swing.JButton jButtonCancelarAddMaterialEnvasar;
    public javax.swing.JButton jButtonCancelarMaterialEnvasar;
    public javax.swing.JButton jButtonEliminarMaterialEnvasar;
    public javax.swing.JButton jButtonModificarMaterialEnvasar;
    public javax.swing.JButton jButtonNuevoMaterialEnvasar;
    public javax.swing.JButton jButtonPrimeroMaterialEnvasar;
    public javax.swing.JButton jButtonQuitarBuscarMaterialEnvasar;
    public javax.swing.JButton jButtonSiguienteMaterialEnvasar;
    public javax.swing.JButton jButtonUltimoMaterialEnvasar;
    public javax.swing.JCheckBox jCheckBoxTenemosMaterialEnvasar;
    public javax.swing.JComboBox jComboBoxBuscarMaterialEnvasar;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabelIdMaterialEnvasar;
    public javax.swing.JLabel jLabelPosicionMaterialEnvasar;
    public javax.swing.JList jListMaterialEnvasar;
    public javax.swing.JPanel jPanelEdicionDatosMaterialEnvasar;
    public javax.swing.JPanel jPanelListaMaterialEnvasar;
    public javax.swing.JPanel jPanelMaterialEnvasado;
    public javax.swing.JPanel jPanelProductosBuscar2;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPaneListaMaterial;
    public javax.swing.JToolBar.Separator jSeparator10;
    public javax.swing.JToolBar.Separator jSeparator8;
    public javax.swing.JToolBar.Separator jSeparator9;
    public javax.swing.JTextArea jTextAreaMaterialEnvasar;
    public javax.swing.JTextField jTextFieldBuscarMaterialEnvasar;
    public javax.swing.JToolBar jToolBarMaterialEnvasar;
    // End of variables declaration//GEN-END:variables
}
