/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.sacyl.caza.farmacia.vista;

/**
 *
 * @author enrique
 */
public class PanelMaterialElaboracion extends javax.swing.JPanel {

    /**
     * 
     * @param add true para mostrar los botones de añadir y cancelar( añadir)
     */
    public PanelMaterialElaboracion(boolean add) {
        initComponents();
        jButtonAceptarMaterialElaborar.setVisible(false);
        jButtonCancelarMaterialElaborar.setVisible(false);
        jButtonAddMaterialElaborar.setVisible(add);
        jButtonCancelarAddMaterialElaborar.setVisible(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaterialElaborar = new javax.swing.JPanel();
        jToolBarMaterialElaborar = new javax.swing.JToolBar();
        jButtonPrimeroMaterialElaborar = new javax.swing.JButton();
        jButtonAtrasMaterialElaborar = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jLabelPosicionMaterialElaborar = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteMaterialElaborar = new javax.swing.JButton();
        jButtonUltimoMaterialElaborar = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jButtonNuevoMaterialElaborar = new javax.swing.JButton();
        jButtonModificarMaterialElaborar = new javax.swing.JButton();
        jButtonEliminarMaterialElaborar = new javax.swing.JButton();
        jPanelProductosBuscar3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxBuscarMaterialElaborar = new javax.swing.JComboBox();
        jTextFieldBuscarMaterialElaborar = new javax.swing.JTextField();
        jButtonBuscarMaterialElaborar = new javax.swing.JButton();
        jButtonQuitarBuscarMaterialElaborar = new javax.swing.JButton();
        jPanelListaMaterialElaborar = new javax.swing.JPanel();
        jScrollPaneListaMaterial = new javax.swing.JScrollPane();
        jListMaterialElaborar = new javax.swing.JList();
        jLabel20 = new javax.swing.JLabel();
        jPanelEdicionDatosMaterialElaborar = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButtonCancelarMaterialElaborar = new javax.swing.JButton();
        jButtonAceptarMaterialElaborar = new javax.swing.JButton();
        jLabelIdMaterialElaborar = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaMaterialElaborar = new javax.swing.JTextArea();
        jCheckBoxTenemosMaterialElaborar = new javax.swing.JCheckBox();
        jButtonAddMaterialElaborar = new javax.swing.JButton();
        jButtonCancelarAddMaterialElaborar = new javax.swing.JButton();

        jPanelMaterialElaborar.setBackground(new java.awt.Color(255, 255, 255));

        jToolBarMaterialElaborar.setBackground(new java.awt.Color(237, 255, 255));
        jToolBarMaterialElaborar.setFloatable(false);
        jToolBarMaterialElaborar.setRollover(true);

        jButtonPrimeroMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroMaterialElaborar.setToolTipText("Se coloca en el primer material para elaborar");
        jButtonPrimeroMaterialElaborar.setEnabled(false);
        jButtonPrimeroMaterialElaborar.setFocusable(false);
        jButtonPrimeroMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonPrimeroMaterialElaborar);

        jButtonAtrasMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasMaterialElaborar.setToolTipText("Se coloca en el material par elaborar anterior");
        jButtonAtrasMaterialElaborar.setEnabled(false);
        jButtonAtrasMaterialElaborar.setFocusable(false);
        jButtonAtrasMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonAtrasMaterialElaborar);
        jToolBarMaterialElaborar.add(jSeparator11);

        jLabelPosicionMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionMaterialElaborar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionMaterialElaborar.setText("Maquinaria 200 de 300");
        jLabelPosicionMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarMaterialElaborar.add(jLabelPosicionMaterialElaborar);
        jToolBarMaterialElaborar.add(jSeparator12);

        jButtonSiguienteMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteMaterialElaborar.setToolTipText("Se coloca en el material para elaborar siguiente");
        jButtonSiguienteMaterialElaborar.setFocusable(false);
        jButtonSiguienteMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonSiguienteMaterialElaborar);

        jButtonUltimoMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoMaterialElaborar.setToolTipText("Se coloca en el último material para elaborar");
        jButtonUltimoMaterialElaborar.setFocusable(false);
        jButtonUltimoMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonUltimoMaterialElaborar);

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator13.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarMaterialElaborar.add(jSeparator13);

        jButtonNuevoMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoAgregar.png"))); // NOI18N
        jButtonNuevoMaterialElaborar.setToolTipText("Crea un nuevo material para elaborar");
        jButtonNuevoMaterialElaborar.setFocusable(false);
        jButtonNuevoMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonNuevoMaterialElaborar);

        jButtonModificarMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoEditar.png"))); // NOI18N
        jButtonModificarMaterialElaborar.setToolTipText("Permite modificar el material para elaborar actual");
        jButtonModificarMaterialElaborar.setFocusable(false);
        jButtonModificarMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonModificarMaterialElaborar);

        jButtonEliminarMaterialElaborar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoBorrar.png"))); // NOI18N
        jButtonEliminarMaterialElaborar.setToolTipText("Elimina el material para elaborar actual");
        jButtonEliminarMaterialElaborar.setFocusable(false);
        jButtonEliminarMaterialElaborar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarMaterialElaborar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialElaborar.add(jButtonEliminarMaterialElaborar);

        jPanelProductosBuscar3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Buscar por:");

        jComboBoxBuscarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarMaterialElaborar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Material para elaborar", "Tenemos" }));
        jComboBoxBuscarMaterialElaborar.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarMaterialElaborar.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarMaterialElaborar.setMnemonic('B');
        jButtonBuscarMaterialElaborar.setText("Buscar");
        jButtonBuscarMaterialElaborar.setToolTipText("Buscar productos que coincidan con los criterios elegidos");

        jButtonQuitarBuscarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarMaterialElaborar.setMnemonic('Q');
        jButtonQuitarBuscarMaterialElaborar.setText("Quitar búsqueda");
        jButtonQuitarBuscarMaterialElaborar.setToolTipText("Volver a mostrar todos los datos");

        javax.swing.GroupLayout jPanelProductosBuscar3Layout = new javax.swing.GroupLayout(jPanelProductosBuscar3);
        jPanelProductosBuscar3.setLayout(jPanelProductosBuscar3Layout);
        jPanelProductosBuscar3Layout.setHorizontalGroup(
            jPanelProductosBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarMaterialElaborar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscar3Layout.setVerticalGroup(
            jPanelProductosBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarMaterialElaborar)
                    .addComponent(jButtonQuitarBuscarMaterialElaborar))
                .addContainerGap())
        );

        jPanelListaMaterialElaborar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaMaterialElaborar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true), "Lista de materiales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jListMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jListMaterialElaborar.setToolTipText("Si se selecciona un material para elaborar se verán sus datos a la derecha");
        jScrollPaneListaMaterial.setViewportView(jListMaterialElaborar);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("¿Tenemos?- Material");

        javax.swing.GroupLayout jPanelListaMaterialElaborarLayout = new javax.swing.GroupLayout(jPanelListaMaterialElaborar);
        jPanelListaMaterialElaborar.setLayout(jPanelListaMaterialElaborarLayout);
        jPanelListaMaterialElaborarLayout.setHorizontalGroup(
            jPanelListaMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaMaterialElaborarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelListaMaterialElaborarLayout.setVerticalGroup(
            jPanelListaMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaMaterialElaborarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaMaterial)
                .addContainerGap())
        );

        jPanelEdicionDatosMaterialElaborar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosMaterialElaborar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Edición de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosMaterialElaborar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setText("ID:");
        jPanelEdicionDatosMaterialElaborar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Material elaborar:");
        jPanelEdicionDatosMaterialElaborar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setText("Tenemos:");
        jPanelEdicionDatosMaterialElaborar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButtonCancelarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarMaterialElaborar.setMnemonic('C');
        jButtonCancelarMaterialElaborar.setText("Cancelar");
        jPanelEdicionDatosMaterialElaborar.add(jButtonCancelarMaterialElaborar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jButtonAceptarMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAceptarMaterialElaborar.setMnemonic('A');
        jButtonAceptarMaterialElaborar.setText("Aceptar");
        jPanelEdicionDatosMaterialElaborar.add(jButtonAceptarMaterialElaborar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabelIdMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIdMaterialElaborar.setText("44");
        jPanelEdicionDatosMaterialElaborar.add(jLabelIdMaterialElaborar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, -1));

        jTextAreaMaterialElaborar.setEditable(false);
        jTextAreaMaterialElaborar.setColumns(20);
        jTextAreaMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaMaterialElaborar.setLineWrap(true);
        jTextAreaMaterialElaborar.setRows(5);
        jTextAreaMaterialElaborar.setToolTipText("Nombre del material para elaborar");
        jScrollPane9.setViewportView(jTextAreaMaterialElaborar);

        jPanelEdicionDatosMaterialElaborar.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 60));

        jCheckBoxTenemosMaterialElaborar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTenemosMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxTenemosMaterialElaborar.setText("Sí");
        jCheckBoxTenemosMaterialElaborar.setEnabled(false);
        jPanelEdicionDatosMaterialElaborar.add(jCheckBoxTenemosMaterialElaborar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 255, -1, -1));

        jButtonAddMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAddMaterialElaborar.setText("Añadir");

        jButtonCancelarAddMaterialElaborar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarAddMaterialElaborar.setText("Cancelar");

        javax.swing.GroupLayout jPanelMaterialElaborarLayout = new javax.swing.GroupLayout(jPanelMaterialElaborar);
        jPanelMaterialElaborar.setLayout(jPanelMaterialElaborarLayout);
        jPanelMaterialElaborarLayout.setHorizontalGroup(
            jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMaterialElaborar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMaterialElaborarLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductosBuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMaterialElaborarLayout.createSequentialGroup()
                        .addComponent(jPanelListaMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMaterialElaborarLayout.createSequentialGroup()
                                .addComponent(jButtonAddMaterialElaborar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelarAddMaterialElaborar))
                            .addComponent(jPanelEdicionDatosMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelMaterialElaborarLayout.setVerticalGroup(
            jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialElaborarLayout.createSequentialGroup()
                .addComponent(jToolBarMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelProductosBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEdicionDatosMaterialElaborar, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPanelListaMaterialElaborar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelMaterialElaborarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMaterialElaborar)
                    .addComponent(jButtonCancelarAddMaterialElaborar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelMaterialElaborar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelMaterialElaborar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarMaterialElaborar;
    public javax.swing.JButton jButtonAddMaterialElaborar;
    public javax.swing.JButton jButtonAtrasMaterialElaborar;
    public javax.swing.JButton jButtonBuscarMaterialElaborar;
    public javax.swing.JButton jButtonCancelarAddMaterialElaborar;
    public javax.swing.JButton jButtonCancelarMaterialElaborar;
    public javax.swing.JButton jButtonEliminarMaterialElaborar;
    public javax.swing.JButton jButtonModificarMaterialElaborar;
    public javax.swing.JButton jButtonNuevoMaterialElaborar;
    public javax.swing.JButton jButtonPrimeroMaterialElaborar;
    public javax.swing.JButton jButtonQuitarBuscarMaterialElaborar;
    public javax.swing.JButton jButtonSiguienteMaterialElaborar;
    public javax.swing.JButton jButtonUltimoMaterialElaborar;
    public javax.swing.JCheckBox jCheckBoxTenemosMaterialElaborar;
    public javax.swing.JComboBox jComboBoxBuscarMaterialElaborar;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabelIdMaterialElaborar;
    public javax.swing.JLabel jLabelPosicionMaterialElaborar;
    public javax.swing.JList jListMaterialElaborar;
    public javax.swing.JPanel jPanelEdicionDatosMaterialElaborar;
    public javax.swing.JPanel jPanelListaMaterialElaborar;
    public javax.swing.JPanel jPanelMaterialElaborar;
    public javax.swing.JPanel jPanelProductosBuscar3;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JScrollPane jScrollPaneListaMaterial;
    public javax.swing.JToolBar.Separator jSeparator11;
    public javax.swing.JToolBar.Separator jSeparator12;
    public javax.swing.JToolBar.Separator jSeparator13;
    public javax.swing.JTextArea jTextAreaMaterialElaborar;
    public javax.swing.JTextField jTextFieldBuscarMaterialElaborar;
    public javax.swing.JToolBar jToolBarMaterialElaborar;
    // End of variables declaration//GEN-END:variables
}
