/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.sacyl.caza.farmacia.vista;

/**
 *
 * @author enrique
 */
public class PanelMaquinaria extends javax.swing.JPanel {

    /**
     * 
     * @param add true para que se vean los botones de añadir y cancelar el añadir
     */
    public PanelMaquinaria(boolean add) {
        initComponents();
        jButtonAceptarMaquinaria.setVisible(false);
        jButtonCancelarMaquinaria.setVisible(false);
        jButtonAddMaquinaria.setVisible(add);
        jButtonCancelarAddMaquinaria.setVisible(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaquinaria = new javax.swing.JPanel();
        jToolBarMaquinaria = new javax.swing.JToolBar();
        jButtonPrimeroMaquinaria = new javax.swing.JButton();
        jButtonAtrasMaquinaria = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jLabelPosicionMaquinaria = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteMaquinaria = new javax.swing.JButton();
        jButtonUltimoMaquinaria = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButtonNuevoMaquinaria = new javax.swing.JButton();
        jButtonModificarMaquinaria = new javax.swing.JButton();
        jButtonEliminarMaquinaria = new javax.swing.JButton();
        jPanelProductosBuscar1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxBuscarMaquinaria = new javax.swing.JComboBox();
        jTextFieldBuscarMaquinaria = new javax.swing.JTextField();
        jButtonBuscarMaquinaria = new javax.swing.JButton();
        jButtonQuitarBuscarMaquinaria = new javax.swing.JButton();
        jPanelListaMaquinaria = new javax.swing.JPanel();
        jScrollPaneListaMaquinaria = new javax.swing.JScrollPane();
        jListMaquinaria = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jPanelEdicionDatosMaquinaria = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButtonCancelarMaquinaria = new javax.swing.JButton();
        jButtonAceptarMaquinaria = new javax.swing.JButton();
        jLabelIdMaquinaria = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMaquinaria = new javax.swing.JTextArea();
        jCheckBoxTenemosMaquinaria = new javax.swing.JCheckBox();
        jButtonAddMaquinaria = new javax.swing.JButton();
        jButtonCancelarAddMaquinaria = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(975, 605));

        jPanelMaquinaria.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMaquinaria.setPreferredSize(new java.awt.Dimension(975, 605));

        jToolBarMaquinaria.setBackground(new java.awt.Color(237, 255, 255));
        jToolBarMaquinaria.setFloatable(false);
        jToolBarMaquinaria.setRollover(true);

        jButtonPrimeroMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroMaquinaria.setToolTipText("Se coloca en la primera maquinaria");
        jButtonPrimeroMaquinaria.setEnabled(false);
        jButtonPrimeroMaquinaria.setFocusable(false);
        jButtonPrimeroMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonPrimeroMaquinaria);

        jButtonAtrasMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasMaquinaria.setToolTipText("Se coloca en la maquinaria anterior");
        jButtonAtrasMaquinaria.setEnabled(false);
        jButtonAtrasMaquinaria.setFocusable(false);
        jButtonAtrasMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonAtrasMaquinaria);
        jToolBarMaquinaria.add(jSeparator5);

        jLabelPosicionMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionMaquinaria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionMaquinaria.setText("Maquinaria 200 de 300");
        jLabelPosicionMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarMaquinaria.add(jLabelPosicionMaquinaria);
        jToolBarMaquinaria.add(jSeparator6);

        jButtonSiguienteMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteMaquinaria.setToolTipText("Se coloca en la maquinaria siguiente");
        jButtonSiguienteMaquinaria.setFocusable(false);
        jButtonSiguienteMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonSiguienteMaquinaria);

        jButtonUltimoMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoMaquinaria.setToolTipText("Se coloca en la última maquinaria");
        jButtonUltimoMaquinaria.setFocusable(false);
        jButtonUltimoMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonUltimoMaquinaria);

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator7.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarMaquinaria.add(jSeparator7);

        jButtonNuevoMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoAgregar.png"))); // NOI18N
        jButtonNuevoMaquinaria.setToolTipText("Crea un nueva maquinaria");
        jButtonNuevoMaquinaria.setFocusable(false);
        jButtonNuevoMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonNuevoMaquinaria);

        jButtonModificarMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoEditar.png"))); // NOI18N
        jButtonModificarMaquinaria.setToolTipText("Permite modificar la maquinaria actual");
        jButtonModificarMaquinaria.setFocusable(false);
        jButtonModificarMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonModificarMaquinaria);

        jButtonEliminarMaquinaria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoBorrar.png"))); // NOI18N
        jButtonEliminarMaquinaria.setToolTipText("Elimina la maquinaria actual");
        jButtonEliminarMaquinaria.setFocusable(false);
        jButtonEliminarMaquinaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarMaquinaria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaquinaria.add(jButtonEliminarMaquinaria);

        jPanelProductosBuscar1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Buscar por:");

        jComboBoxBuscarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarMaquinaria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maquinaria", "Tenemos" }));
        jComboBoxBuscarMaquinaria.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarMaquinaria.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarMaquinaria.setMnemonic('B');
        jButtonBuscarMaquinaria.setText("Buscar");
        jButtonBuscarMaquinaria.setToolTipText("Buscar productos que coincidan con los criterios elegidos");

        jButtonQuitarBuscarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarMaquinaria.setMnemonic('Q');
        jButtonQuitarBuscarMaquinaria.setText("Quitar búsqueda");
        jButtonQuitarBuscarMaquinaria.setToolTipText("Volver a mostrar todos los datos");

        javax.swing.GroupLayout jPanelProductosBuscar1Layout = new javax.swing.GroupLayout(jPanelProductosBuscar1);
        jPanelProductosBuscar1.setLayout(jPanelProductosBuscar1Layout);
        jPanelProductosBuscar1Layout.setHorizontalGroup(
            jPanelProductosBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarMaquinaria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscar1Layout.setVerticalGroup(
            jPanelProductosBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarMaquinaria)
                    .addComponent(jButtonQuitarBuscarMaquinaria))
                .addContainerGap())
        );

        jPanelListaMaquinaria.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaMaquinaria.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true), "Lista de maquinaria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jListMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jListMaquinaria.setToolTipText("Si se selecciona una maquinaria se verán sus datos a la derecha");
        jScrollPaneListaMaquinaria.setViewportView(jListMaquinaria);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("¿Tenemos?- Maquinaria");

        javax.swing.GroupLayout jPanelListaMaquinariaLayout = new javax.swing.GroupLayout(jPanelListaMaquinaria);
        jPanelListaMaquinaria.setLayout(jPanelListaMaquinariaLayout);
        jPanelListaMaquinariaLayout.setHorizontalGroup(
            jPanelListaMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaMaquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelListaMaquinariaLayout.setVerticalGroup(
            jPanelListaMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaMaquinariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaMaquinaria)
                .addContainerGap())
        );

        jPanelEdicionDatosMaquinaria.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosMaquinaria.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Edición de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosMaquinaria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("ID:");
        jPanelEdicionDatosMaquinaria.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Maquinaria:");
        jPanelEdicionDatosMaquinaria.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Tenemos:");
        jPanelEdicionDatosMaquinaria.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButtonCancelarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarMaquinaria.setMnemonic('C');
        jButtonCancelarMaquinaria.setText("Cancelar");
        jPanelEdicionDatosMaquinaria.add(jButtonCancelarMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jButtonAceptarMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAceptarMaquinaria.setMnemonic('A');
        jButtonAceptarMaquinaria.setText("Aceptar");
        jPanelEdicionDatosMaquinaria.add(jButtonAceptarMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabelIdMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIdMaquinaria.setText("44");
        jPanelEdicionDatosMaquinaria.add(jLabelIdMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, -1));

        jTextAreaMaquinaria.setEditable(false);
        jTextAreaMaquinaria.setColumns(20);
        jTextAreaMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaMaquinaria.setLineWrap(true);
        jTextAreaMaquinaria.setRows(5);
        jTextAreaMaquinaria.setToolTipText("Nombre de la maquinaria");
        jScrollPane5.setViewportView(jTextAreaMaquinaria);

        jPanelEdicionDatosMaquinaria.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 290, 60));

        jCheckBoxTenemosMaquinaria.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxTenemosMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxTenemosMaquinaria.setText("Sí");
        jCheckBoxTenemosMaquinaria.setToolTipText("");
        jCheckBoxTenemosMaquinaria.setEnabled(false);
        jPanelEdicionDatosMaquinaria.add(jCheckBoxTenemosMaquinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 255, -1, -1));

        jButtonAddMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAddMaquinaria.setText("Añadir");

        jButtonCancelarAddMaquinaria.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarAddMaquinaria.setText("Cancelar");

        javax.swing.GroupLayout jPanelMaquinariaLayout = new javax.swing.GroupLayout(jPanelMaquinaria);
        jPanelMaquinaria.setLayout(jPanelMaquinariaLayout);
        jPanelMaquinariaLayout.setHorizontalGroup(
            jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMaquinariaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductosBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMaquinariaLayout.createSequentialGroup()
                        .addComponent(jPanelListaMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMaquinariaLayout.createSequentialGroup()
                                .addComponent(jButtonAddMaquinaria)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelarAddMaquinaria))
                            .addComponent(jPanelEdicionDatosMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelMaquinariaLayout.setVerticalGroup(
            jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaquinariaLayout.createSequentialGroup()
                .addComponent(jToolBarMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelProductosBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEdicionDatosMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPanelListaMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMaquinariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMaquinaria)
                    .addComponent(jButtonCancelarAddMaquinaria))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelMaquinaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanelMaquinaria, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarMaquinaria;
    public javax.swing.JButton jButtonAddMaquinaria;
    public javax.swing.JButton jButtonAtrasMaquinaria;
    public javax.swing.JButton jButtonBuscarMaquinaria;
    public javax.swing.JButton jButtonCancelarAddMaquinaria;
    public javax.swing.JButton jButtonCancelarMaquinaria;
    public javax.swing.JButton jButtonEliminarMaquinaria;
    public javax.swing.JButton jButtonModificarMaquinaria;
    public javax.swing.JButton jButtonNuevoMaquinaria;
    public javax.swing.JButton jButtonPrimeroMaquinaria;
    public javax.swing.JButton jButtonQuitarBuscarMaquinaria;
    public javax.swing.JButton jButtonSiguienteMaquinaria;
    public javax.swing.JButton jButtonUltimoMaquinaria;
    public javax.swing.JCheckBox jCheckBoxTenemosMaquinaria;
    public javax.swing.JComboBox jComboBoxBuscarMaquinaria;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelIdMaquinaria;
    public javax.swing.JLabel jLabelPosicionMaquinaria;
    public javax.swing.JList jListMaquinaria;
    public javax.swing.JPanel jPanelEdicionDatosMaquinaria;
    public javax.swing.JPanel jPanelListaMaquinaria;
    public javax.swing.JPanel jPanelMaquinaria;
    public javax.swing.JPanel jPanelProductosBuscar1;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPaneListaMaquinaria;
    public javax.swing.JToolBar.Separator jSeparator5;
    public javax.swing.JToolBar.Separator jSeparator6;
    public javax.swing.JToolBar.Separator jSeparator7;
    public javax.swing.JTextArea jTextAreaMaquinaria;
    public javax.swing.JTextField jTextFieldBuscarMaquinaria;
    public javax.swing.JToolBar jToolBarMaquinaria;
    // End of variables declaration//GEN-END:variables
}
