/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.sacyl.caza.farmacia.vista;

/**
 *
 * @author enrique
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * 
     * @param add true para mostrar los botones de añadir/cancelar un producto a un medicamento
     */
    public PanelProductos(boolean add) {
        initComponents();
        jButtonAceptarProductos.setVisible(false);
        jButtonCancelarProductos.setVisible(false);
        jButtonAddProducto.setVisible(add);
        jButtonCancelarAddProducto.setVisible(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProductos = new javax.swing.JPanel();
        jToolBarProductos = new javax.swing.JToolBar();
        jButtonPrimeroProductos = new javax.swing.JButton();
        jButtonAtrasProductos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabelPosicionProducto = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteProductos = new javax.swing.JButton();
        jButtonUltimoProductos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonNuevoProductos = new javax.swing.JButton();
        jButtonModificarProductos = new javax.swing.JButton();
        jButtonEliminarProductos = new javax.swing.JButton();
        jPanelListaProductos = new javax.swing.JPanel();
        jScrollPaneListaProducto = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        jPanelEdicionDatosProductos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonCancelarProductos = new javax.swing.JButton();
        jButtonAceptarProductos = new javax.swing.JButton();
        jLabelIdProductos = new javax.swing.JLabel();
        jTextFieldEstanteProductos = new javax.swing.JTextField();
        jTextFieldReferenciaProductos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservacionesProductos = new javax.swing.JTextArea();
        jComboBoxActivoProductos = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaComponenteProductos = new javax.swing.JTextArea();
        jPanelProductosBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxBuscarProductos = new javax.swing.JComboBox();
        jTextFieldBuscarProductos = new javax.swing.JTextField();
        jButtonBuscarProductos = new javax.swing.JButton();
        jButtonQuitarBuscarProductos = new javax.swing.JButton();
        jButtonAddProducto = new javax.swing.JButton();
        jButtonCancelarAddProducto = new javax.swing.JButton();

        jPanelProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jToolBarProductos.setBackground(new java.awt.Color(237, 255, 255));
        jToolBarProductos.setFloatable(false);
        jToolBarProductos.setRollover(true);

        jButtonPrimeroProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroProductos.setToolTipText("Se coloca en el primer producto");
        jButtonPrimeroProductos.setEnabled(false);
        jButtonPrimeroProductos.setFocusable(false);
        jButtonPrimeroProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonPrimeroProductos);

        jButtonAtrasProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasProductos.setToolTipText("Se coloca en el producto anterior");
        jButtonAtrasProductos.setEnabled(false);
        jButtonAtrasProductos.setFocusable(false);
        jButtonAtrasProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonAtrasProductos);
        jToolBarProductos.add(jSeparator3);

        jLabelPosicionProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionProducto.setText("Producto 200 de 300");
        jLabelPosicionProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarProductos.add(jLabelPosicionProducto);
        jToolBarProductos.add(jSeparator4);

        jButtonSiguienteProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteProductos.setToolTipText("Se coloca en el producto siguiente");
        jButtonSiguienteProductos.setFocusable(false);
        jButtonSiguienteProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonSiguienteProductos);

        jButtonUltimoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoProductos.setToolTipText("Se coloca en el último producto");
        jButtonUltimoProductos.setFocusable(false);
        jButtonUltimoProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonUltimoProductos);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator2.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarProductos.add(jSeparator2);

        jButtonNuevoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoAgregar.png"))); // NOI18N
        jButtonNuevoProductos.setToolTipText("Crea un nuevo producto");
        jButtonNuevoProductos.setFocusable(false);
        jButtonNuevoProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonNuevoProductos);

        jButtonModificarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoEditar.png"))); // NOI18N
        jButtonModificarProductos.setToolTipText("Permite modificar el producto actual");
        jButtonModificarProductos.setFocusable(false);
        jButtonModificarProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonModificarProductos);

        jButtonEliminarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/productoBorrar.png"))); // NOI18N
        jButtonEliminarProductos.setToolTipText("Elimina el producto actual");
        jButtonEliminarProductos.setFocusable(false);
        jButtonEliminarProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonEliminarProductos);

        jPanelListaProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true), "Lista de productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jListProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jListProductos.setToolTipText("Si se selecciona un producto se verán sus datos a la derecha");
        jScrollPaneListaProducto.setViewportView(jListProductos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Referencia- Componente");

        javax.swing.GroupLayout jPanelListaProductosLayout = new javax.swing.GroupLayout(jPanelListaProductos);
        jPanelListaProductos.setLayout(jPanelListaProductosLayout);
        jPanelListaProductosLayout.setHorizontalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelListaProductosLayout.setVerticalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaProducto)
                .addContainerGap())
        );

        jPanelEdicionDatosProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Edición de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("ID:");
        jPanelEdicionDatosProductos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Componente:");
        jPanelEdicionDatosProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Referencia:");
        jPanelEdicionDatosProductos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Activo:");
        jPanelEdicionDatosProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Observaciones:");
        jPanelEdicionDatosProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Estante:");
        jPanelEdicionDatosProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jButtonCancelarProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarProductos.setMnemonic('C');
        jButtonCancelarProductos.setText("Cancelar");
        jPanelEdicionDatosProductos.add(jButtonCancelarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        jButtonAceptarProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAceptarProductos.setMnemonic('A');
        jButtonAceptarProductos.setText("Aceptar");
        jPanelEdicionDatosProductos.add(jButtonAceptarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jLabelIdProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIdProductos.setText("44");
        jPanelEdicionDatosProductos.add(jLabelIdProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 60, -1));

        jTextFieldEstanteProductos.setEditable(false);
        jTextFieldEstanteProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldEstanteProductos.setText("jTextField2");
        jPanelEdicionDatosProductos.add(jTextFieldEstanteProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 310, 30));

        jTextFieldReferenciaProductos.setEditable(false);
        jTextFieldReferenciaProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextFieldReferenciaProductos.setText("jTextField2");
        jTextFieldReferenciaProductos.setToolTipText("Está formada por una letra+número, las letras posibles son 's' para sólidos, 'l' para líquidos, 'c' para cápsulas y '#' para el resto");
        jPanelEdicionDatosProductos.add(jTextFieldReferenciaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 310, 30));

        jTextAreaObservacionesProductos.setEditable(false);
        jTextAreaObservacionesProductos.setColumns(20);
        jTextAreaObservacionesProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaObservacionesProductos.setLineWrap(true);
        jTextAreaObservacionesProductos.setRows(2);
        jScrollPane2.setViewportView(jTextAreaObservacionesProductos);

        jPanelEdicionDatosProductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 310, 60));

        jComboBoxActivoProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxActivoProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1" }));
        jPanelEdicionDatosProductos.add(jComboBoxActivoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 310, 30));

        jTextAreaComponenteProductos.setEditable(false);
        jTextAreaComponenteProductos.setColumns(20);
        jTextAreaComponenteProductos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaComponenteProductos.setLineWrap(true);
        jTextAreaComponenteProductos.setRows(2);
        jScrollPane3.setViewportView(jTextAreaComponenteProductos);

        jPanelEdicionDatosProductos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 310, 50));

        jPanelProductosBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por:");

        jComboBoxBuscarProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Referencia", "Activo" }));
        jComboBoxBuscarProductos.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarProductos.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarProductos.setMnemonic('B');
        jButtonBuscarProductos.setText("Buscar");
        jButtonBuscarProductos.setToolTipText("Buscar productos que coincidan con los criterios elegidos");

        jButtonQuitarBuscarProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarProductos.setMnemonic('Q');
        jButtonQuitarBuscarProductos.setText("Quitar búsqueda");
        jButtonQuitarBuscarProductos.setToolTipText("Volver a mostrar todos los datos");

        javax.swing.GroupLayout jPanelProductosBuscarLayout = new javax.swing.GroupLayout(jPanelProductosBuscar);
        jPanelProductosBuscar.setLayout(jPanelProductosBuscarLayout);
        jPanelProductosBuscarLayout.setHorizontalGroup(
            jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscarLayout.setVerticalGroup(
            jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProductos)
                    .addComponent(jButtonQuitarBuscarProductos))
                .addContainerGap())
        );

        jButtonAddProducto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAddProducto.setText("Añadir");

        jButtonCancelarAddProducto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarAddProducto.setText("Cancelar");

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelProductosLayout.createSequentialGroup()
                        .addComponent(jPanelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelProductosLayout.createSequentialGroup()
                                .addComponent(jButtonAddProducto)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelarAddProducto))
                            .addComponent(jPanelEdicionDatosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addComponent(jToolBarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelProductosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEdicionDatosProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPanelListaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddProducto)
                    .addComponent(jButtonCancelarAddProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarProductos;
    public javax.swing.JButton jButtonAddProducto;
    public javax.swing.JButton jButtonAtrasProductos;
    public javax.swing.JButton jButtonBuscarProductos;
    public javax.swing.JButton jButtonCancelarAddProducto;
    public javax.swing.JButton jButtonCancelarProductos;
    public javax.swing.JButton jButtonEliminarProductos;
    public javax.swing.JButton jButtonModificarProductos;
    public javax.swing.JButton jButtonNuevoProductos;
    public javax.swing.JButton jButtonPrimeroProductos;
    public javax.swing.JButton jButtonQuitarBuscarProductos;
    public javax.swing.JButton jButtonSiguienteProductos;
    public javax.swing.JButton jButtonUltimoProductos;
    public javax.swing.JComboBox jComboBoxActivoProductos;
    public javax.swing.JComboBox jComboBoxBuscarProductos;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelIdProductos;
    public javax.swing.JLabel jLabelPosicionProducto;
    public javax.swing.JList jListProductos;
    public javax.swing.JPanel jPanelEdicionDatosProductos;
    public javax.swing.JPanel jPanelListaProductos;
    public javax.swing.JPanel jPanelProductos;
    public javax.swing.JPanel jPanelProductosBuscar;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPaneListaProducto;
    public javax.swing.JToolBar.Separator jSeparator2;
    public javax.swing.JToolBar.Separator jSeparator3;
    public javax.swing.JToolBar.Separator jSeparator4;
    public javax.swing.JTextArea jTextAreaComponenteProductos;
    public javax.swing.JTextArea jTextAreaObservacionesProductos;
    public javax.swing.JTextField jTextFieldBuscarProductos;
    public javax.swing.JTextField jTextFieldEstanteProductos;
    public javax.swing.JTextField jTextFieldReferenciaProductos;
    public javax.swing.JToolBar jToolBarProductos;
    // End of variables declaration//GEN-END:variables
}
