/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.sacyl.caza.farmacia.vista;

import es.sacyl.caza.farmacia.controlador.ControladorReenvasados;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author enrique
 */
public class VentanaReenvasados extends javax.swing.JFrame {

    ControladorReenvasados control;
    public static final VentanaReenvasados instance= new VentanaReenvasados(null, false);
    /**
     * Creates new form VentanaReenvasados
     */
    private VentanaReenvasados(java.awt.Frame parent, boolean modal) {
        super("Reenvasados");
        initComponents();
        control = new ControladorReenvasados(this);
        jButtonAceptarReenvasados.setVisible(false);
        jButtonCancelarReenvasados.setVisible(false);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(getClass().getResource("/es/sacyl/caza/farmacia/resources/images.jpg"));

        
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogImprimirReenvasados = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldLoteReenvasados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldFechaCaducidadReenvasados = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxDatosExtra = new javax.swing.JCheckBox();
        jButtonVistaPreviaReenvasados = new javax.swing.JButton();
        jButtonVolverReenvasados = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPopupMenuCopiarPegar = new javax.swing.JPopupMenu();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemPegar = new javax.swing.JMenuItem();
        jPanelReenvasado = new javax.swing.JPanel();
        jToolBarMaterialEnvasar = new javax.swing.JToolBar();
        jButtonPrimeroReenvasados = new javax.swing.JButton();
        jButtonAtrasReenvasados = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabelPosicionReenvasados = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteReenvasados = new javax.swing.JButton();
        jButtonUltimoReenvasados = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButtonNuevoReenvasados = new javax.swing.JButton();
        jButtonModificarReenvasados = new javax.swing.JButton();
        jButtonEliminarReenvasados = new javax.swing.JButton();
        jButtonImprimirReenvasados = new javax.swing.JButton();
        jPanelProductosBuscar2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxBuscarReenvasados = new javax.swing.JComboBox();
        jTextFieldBuscarReenvasados = new javax.swing.JTextField();
        jButtonBuscarReenvasados = new javax.swing.JButton();
        jButtonQuitarBuscarReenvasados = new javax.swing.JButton();
        jPanelListaReenvasados = new javax.swing.JPanel();
        jScrollPaneListaMaterial = new javax.swing.JScrollPane();
        jListReenvasados = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jPanelEdicionDatosReenvasados = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButtonCancelarReenvasados = new javax.swing.JButton();
        jButtonAceptarReenvasados = new javax.swing.JButton();
        jLabelIdReenvasados = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaPrincipioActivoReenvasados = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaDescripcionReenvasados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemArchivoNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemArchivoSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEditarModificar = new javax.swing.JMenuItem();
        jMenuItemEditarEliminar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemVerPrimero = new javax.swing.JMenuItem();
        jMenuItemVerAnterior = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerSiguiente = new javax.swing.JMenuItem();
        jMenuItemVerUltimo = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItemImprimir = new javax.swing.JMenuItem();

        jDialogImprimirReenvasados.setAlwaysOnTop(true);
        jDialogImprimirReenvasados.setModal(true);

        jPanel1.setBackground(new java.awt.Color(248, 248, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jTextFieldLoteReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Fecha de caducidad:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Lote:");

        jFormattedTextFieldFechaCaducidadReenvasados.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/yy"))));
        jFormattedTextFieldFechaCaducidadReenvasados.setToolTipText("mes/año (formato: mm/aa)");
        jFormattedTextFieldFechaCaducidadReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Introduzca otros datos que se veran en la etiqueta:");

        jCheckBoxDatosExtra.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxDatosExtra.setText("Mostrar datos extra");
        jCheckBoxDatosExtra.setToolTipText("Muestra hasta 26 caracteres en las etiquetas del campo datos extra, si  el campo es mas largo, sólo se verán los 25 primeros ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLoteReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldFechaCaducidadReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3)
                            .addComponent(jCheckBoxDatosExtra))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLoteReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldFechaCaducidadReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxDatosExtra)
                .addContainerGap())
        );

        jButtonVistaPreviaReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonVistaPreviaReenvasados.setText("Vista previa");

        jButtonVolverReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonVolverReenvasados.setText("Volver");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButtonVistaPreviaReenvasados)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonVolverReenvasados)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVistaPreviaReenvasados)
                    .addComponent(jButtonVolverReenvasados))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogImprimirReenvasadosLayout = new javax.swing.GroupLayout(jDialogImprimirReenvasados.getContentPane());
        jDialogImprimirReenvasados.getContentPane().setLayout(jDialogImprimirReenvasadosLayout);
        jDialogImprimirReenvasadosLayout.setHorizontalGroup(
            jDialogImprimirReenvasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogImprimirReenvasadosLayout.setVerticalGroup(
            jDialogImprimirReenvasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItemCopiar.setText("Copiar (Ctlr+C)");
        jPopupMenuCopiarPegar.add(jMenuItemCopiar);

        jMenuItemPegar.setText("Pegar (Ctlr+V)");
        jPopupMenuCopiarPegar.add(jMenuItemPegar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farmacotecnia->Reenvasados");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanelReenvasado.setBackground(new java.awt.Color(255, 255, 255));

        jToolBarMaterialEnvasar.setBackground(new java.awt.Color(248, 248, 110));
        jToolBarMaterialEnvasar.setFloatable(false);
        jToolBarMaterialEnvasar.setRollover(true);

        jButtonPrimeroReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroReenvasados.setToolTipText("Se coloca en el primer reenvasado");
        jButtonPrimeroReenvasados.setEnabled(false);
        jButtonPrimeroReenvasados.setFocusable(false);
        jButtonPrimeroReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonPrimeroReenvasados);

        jButtonAtrasReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasReenvasados.setToolTipText("Se coloca en el reenvasado anterior");
        jButtonAtrasReenvasados.setEnabled(false);
        jButtonAtrasReenvasados.setFocusable(false);
        jButtonAtrasReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonAtrasReenvasados);
        jToolBarMaterialEnvasar.add(jSeparator8);

        jLabelPosicionReenvasados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionReenvasados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionReenvasados.setText("Maquinaria 200 de 300");
        jLabelPosicionReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarMaterialEnvasar.add(jLabelPosicionReenvasados);
        jToolBarMaterialEnvasar.add(jSeparator9);

        jButtonSiguienteReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteReenvasados.setToolTipText("Se coloca en el reenvasado siguiente");
        jButtonSiguienteReenvasados.setFocusable(false);
        jButtonSiguienteReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonSiguienteReenvasados);

        jButtonUltimoReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoReenvasados.setToolTipText("Se coloca en el último reenvasado");
        jButtonUltimoReenvasados.setFocusable(false);
        jButtonUltimoReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonUltimoReenvasados);

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator10.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator10.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarMaterialEnvasar.add(jSeparator10);

        jButtonNuevoReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/nuevoReenvasado_1.png"))); // NOI18N
        jButtonNuevoReenvasados.setToolTipText("Crea un nuevo reenvasado");
        jButtonNuevoReenvasados.setFocusable(false);
        jButtonNuevoReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonNuevoReenvasados);

        jButtonModificarReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/reenvasadoModificar_1.png"))); // NOI18N
        jButtonModificarReenvasados.setToolTipText("Permite modificar reenvasado actual");
        jButtonModificarReenvasados.setFocusable(false);
        jButtonModificarReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonModificarReenvasados);

        jButtonEliminarReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/reenvasadoBorrar_1.png"))); // NOI18N
        jButtonEliminarReenvasados.setToolTipText("Elimina el reenvasado actual");
        jButtonEliminarReenvasados.setFocusable(false);
        jButtonEliminarReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonEliminarReenvasados);

        jButtonImprimirReenvasados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/reenvasadoImprimir_1.png"))); // NOI18N
        jButtonImprimirReenvasados.setToolTipText("Imprime el reenvasado actual.");
        jButtonImprimirReenvasados.setFocusable(false);
        jButtonImprimirReenvasados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimirReenvasados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarMaterialEnvasar.add(jButtonImprimirReenvasados);

        jPanelProductosBuscar2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Buscar por:");

        jComboBoxBuscarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarReenvasados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descripción", "Datos extra" }));
        jComboBoxBuscarReenvasados.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarReenvasados.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarReenvasados.setMnemonic('B');
        jButtonBuscarReenvasados.setText("Buscar");
        jButtonBuscarReenvasados.setToolTipText("Buscar productos que coincidan con los criterios elegidos");

        jButtonQuitarBuscarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarReenvasados.setMnemonic('Q');
        jButtonQuitarBuscarReenvasados.setText("Quitar búsqueda");
        jButtonQuitarBuscarReenvasados.setToolTipText("Volver a mostrar todos los datos");

        javax.swing.GroupLayout jPanelProductosBuscar2Layout = new javax.swing.GroupLayout(jPanelProductosBuscar2);
        jPanelProductosBuscar2.setLayout(jPanelProductosBuscar2Layout);
        jPanelProductosBuscar2Layout.setHorizontalGroup(
            jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarReenvasados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscar2Layout.setVerticalGroup(
            jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscar2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarReenvasados)
                    .addComponent(jButtonQuitarBuscarReenvasados))
                .addContainerGap())
        );

        jPanelListaReenvasados.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaReenvasados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 51), 2, true), "Lista de reenvasados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jListReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jListReenvasados.setToolTipText("Si se selecciona un reenvasado se verán sus datos a la derecha");
        jScrollPaneListaMaterial.setViewportView(jListReenvasados);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Descripción");

        javax.swing.GroupLayout jPanelListaReenvasadosLayout = new javax.swing.GroupLayout(jPanelListaReenvasados);
        jPanelListaReenvasados.setLayout(jPanelListaReenvasadosLayout);
        jPanelListaReenvasadosLayout.setHorizontalGroup(
            jPanelListaReenvasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaReenvasadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaReenvasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelListaReenvasadosLayout.setVerticalGroup(
            jPanelListaReenvasadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaReenvasadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaMaterial)
                .addContainerGap())
        );

        jPanelEdicionDatosReenvasados.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosReenvasados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), "Edición de datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosReenvasados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("ID:");
        jPanelEdicionDatosReenvasados.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Descripción:");
        jPanelEdicionDatosReenvasados.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Datos extra:");
        jPanelEdicionDatosReenvasados.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jButtonCancelarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonCancelarReenvasados.setMnemonic('C');
        jButtonCancelarReenvasados.setText("Cancelar");
        jPanelEdicionDatosReenvasados.add(jButtonCancelarReenvasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jButtonAceptarReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButtonAceptarReenvasados.setMnemonic('A');
        jButtonAceptarReenvasados.setText("Aceptar");
        jPanelEdicionDatosReenvasados.add(jButtonAceptarReenvasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabelIdReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelIdReenvasados.setText("44");
        jPanelEdicionDatosReenvasados.add(jLabelIdReenvasados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 60, -1));

        jTextAreaPrincipioActivoReenvasados.setEditable(false);
        jTextAreaPrincipioActivoReenvasados.setColumns(20);
        jTextAreaPrincipioActivoReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaPrincipioActivoReenvasados.setLineWrap(true);
        jTextAreaPrincipioActivoReenvasados.setRows(5);
        jTextAreaPrincipioActivoReenvasados.setToolTipText("Datos extra del reenvasado");
        jTextAreaPrincipioActivoReenvasados.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane7.setViewportView(jTextAreaPrincipioActivoReenvasados);

        jPanelEdicionDatosReenvasados.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 290, 60));

        jTextAreaDescripcionReenvasados.setEditable(false);
        jTextAreaDescripcionReenvasados.setColumns(20);
        jTextAreaDescripcionReenvasados.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextAreaDescripcionReenvasados.setLineWrap(true);
        jTextAreaDescripcionReenvasados.setRows(5);
        jTextAreaDescripcionReenvasados.setToolTipText("Descripción del reenvasado");
        jTextAreaDescripcionReenvasados.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane8.setViewportView(jTextAreaDescripcionReenvasados);

        jPanelEdicionDatosReenvasados.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 290, 60));

        javax.swing.GroupLayout jPanelReenvasadoLayout = new javax.swing.GroupLayout(jPanelReenvasado);
        jPanelReenvasado.setLayout(jPanelReenvasadoLayout);
        jPanelReenvasadoLayout.setHorizontalGroup(
            jPanelReenvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMaterialEnvasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelReenvasadoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelReenvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelProductosBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelReenvasadoLayout.createSequentialGroup()
                        .addComponent(jPanelListaReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelEdicionDatosReenvasados, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanelReenvasadoLayout.setVerticalGroup(
            jPanelReenvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReenvasadoLayout.createSequentialGroup()
                .addComponent(jToolBarMaterialEnvasar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelProductosBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReenvasadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEdicionDatosReenvasados, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPanelListaReenvasados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItemArchivoNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemArchivoNuevo.setText("Nuevo");
        jMenu1.add(jMenuItemArchivoNuevo);
        jMenu1.add(jSeparator1);

        jMenuItemArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemArchivoSalir.setText("Salir");
        jMenu1.add(jMenuItemArchivoSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItemEditarModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarModificar.setText("Modificar");
        jMenu2.add(jMenuItemEditarModificar);

        jMenuItemEditarEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarEliminar.setText("Eliminar");
        jMenu2.add(jMenuItemEditarEliminar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        jMenuItemVerPrimero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerPrimero.setText("Primero");
        jMenu3.add(jMenuItemVerPrimero);

        jMenuItemVerAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerAnterior.setText("Anterior");
        jMenu3.add(jMenuItemVerAnterior);
        jMenu3.add(jSeparator14);

        jMenuItemVerSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerSiguiente.setText("Siguiente");
        jMenu3.add(jMenuItemVerSiguiente);

        jMenuItemVerUltimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerUltimo.setText("Último");
        jMenu3.add(jMenuItemVerUltimo);
        jMenu3.add(jSeparator15);

        jMenuItemImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemImprimir.setText("Imprimir");
        jMenu3.add(jMenuItemImprimir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelReenvasado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelReenvasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReenvasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReenvasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReenvasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReenvasados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaReenvasados dialog = new VentanaReenvasados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAceptarReenvasados;
    public javax.swing.JButton jButtonAtrasReenvasados;
    public javax.swing.JButton jButtonBuscarReenvasados;
    public javax.swing.JButton jButtonCancelarReenvasados;
    public javax.swing.JButton jButtonEliminarReenvasados;
    public javax.swing.JButton jButtonImprimirReenvasados;
    public javax.swing.JButton jButtonModificarReenvasados;
    public javax.swing.JButton jButtonNuevoReenvasados;
    public javax.swing.JButton jButtonPrimeroReenvasados;
    public javax.swing.JButton jButtonQuitarBuscarReenvasados;
    public javax.swing.JButton jButtonSiguienteReenvasados;
    public javax.swing.JButton jButtonUltimoReenvasados;
    public javax.swing.JButton jButtonVistaPreviaReenvasados;
    public javax.swing.JButton jButtonVolverReenvasados;
    public javax.swing.JCheckBox jCheckBoxDatosExtra;
    public javax.swing.JComboBox jComboBoxBuscarReenvasados;
    public javax.swing.JDialog jDialogImprimirReenvasados;
    public javax.swing.JFormattedTextField jFormattedTextFieldFechaCaducidadReenvasados;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabelIdReenvasados;
    public javax.swing.JLabel jLabelPosicionReenvasados;
    public javax.swing.JList jListReenvasados;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemArchivoNuevo;
    public javax.swing.JMenuItem jMenuItemArchivoSalir;
    public javax.swing.JMenuItem jMenuItemCopiar;
    public javax.swing.JMenuItem jMenuItemEditarEliminar;
    public javax.swing.JMenuItem jMenuItemEditarModificar;
    public javax.swing.JMenuItem jMenuItemImprimir;
    public javax.swing.JMenuItem jMenuItemPegar;
    public javax.swing.JMenuItem jMenuItemVerAnterior;
    public javax.swing.JMenuItem jMenuItemVerPrimero;
    public javax.swing.JMenuItem jMenuItemVerSiguiente;
    public javax.swing.JMenuItem jMenuItemVerUltimo;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanelEdicionDatosReenvasados;
    public javax.swing.JPanel jPanelListaReenvasados;
    public javax.swing.JPanel jPanelProductosBuscar2;
    public javax.swing.JPanel jPanelReenvasado;
    public javax.swing.JPopupMenu jPopupMenuCopiarPegar;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPaneListaMaterial;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JToolBar.Separator jSeparator10;
    public javax.swing.JPopupMenu.Separator jSeparator14;
    public javax.swing.JPopupMenu.Separator jSeparator15;
    public javax.swing.JToolBar.Separator jSeparator8;
    public javax.swing.JToolBar.Separator jSeparator9;
    public javax.swing.JTextArea jTextAreaDescripcionReenvasados;
    public javax.swing.JTextArea jTextAreaPrincipioActivoReenvasados;
    public javax.swing.JTextField jTextFieldBuscarReenvasados;
    public javax.swing.JTextField jTextFieldLoteReenvasados;
    public javax.swing.JToolBar jToolBarMaterialEnvasar;
    // End of variables declaration//GEN-END:variables
}
