/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.sacyl.caza.farmacia.vista;

import es.sacyl.caza.farmacia.controlador.ControladorEtiquetas;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author enrique
 */
public class VentanaEtiquetas extends javax.swing.JFrame {

    private ControladorEtiquetas controlEtiquetas;
    public static final VentanaEtiquetas instance= new VentanaEtiquetas(null, false);
    /**
     * Creates new form VentanaEtiquetas
     */
    private VentanaEtiquetas(java.awt.Frame parent, boolean modal) {
        super("Etiquetas");
        initComponents();
        controlEtiquetas = new ControladorEtiquetas(this);
        //Cambiar la cantidad que se mueve el scroll al girar la rueda del ratón
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        jPanelAceptarCancelar.setVisible(false);
        jPanelAceptarCancelar.setBackground(new java.awt.Color(255,221,174,215));
    }

    private VentanaEtiquetas(java.awt.Frame parent, boolean modal, String nombreMedicamento, boolean nuevaEtiqueta) {
        super("Etiquetas");
        initComponents();
             jButtonAceptarEtiquetas.setVisible(false);
        jButtonCancelarEtiquetas.setVisible(false);
       controlEtiquetas = new ControladorEtiquetas(this, nombreMedicamento, nuevaEtiqueta);
        //Cambiar la cantidad que se mueve el scroll al girar la rueda del ratón
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
     
    }
    
    public void mostrarTodasEtiquetas(){
        controlEtiquetas.cargarTodasEtiquetas();
    }
    
    public void mostrarEtiquetaDeMedicamento(String nombreMedicamento, boolean nuevaEtiqueta){
        controlEtiquetas.cargarEtiquetaDeMedicamento(nombreMedicamento, nuevaEtiqueta);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogImprimirEtiquetas = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonDialogImprimirTipoA = new javax.swing.JRadioButton();
        jRadioButtonDialogImprimirTipoC = new javax.swing.JRadioButton();
        jRadioButtonDialogImprimirTipoB = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextFieldFechaElaboracion = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBoxDialogImprimirUtilizacion = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonDialogImprimirFormatoApli = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButtonDialogImprimirPreview = new javax.swing.JButton();
        jButtonDialogImprimirVolver = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialogImprimirEtiquetasPaciente = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButtonDialogImprimirTipoAPaciente = new javax.swing.JRadioButton();
        jRadioButtonDialogImprimirTipoCPaciente = new javax.swing.JRadioButton();
        jRadioButtonDialogImprimirTipoBPaciente = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldFechaElaboracionPaciente = new javax.swing.JFormattedTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jCheckBoxDialogImprimirUtilizacionPaciente = new javax.swing.JCheckBox();
        jButtonDialogImprimirPreviewPaciente = new javax.swing.JButton();
        jButtonDialogImprimirVolverPaciente = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jCheckBoxNombrePaciente = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNombrePaciente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSpinnerNumeroEtiquetas = new javax.swing.JSpinner();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jRadioButtonDialogImprimirFormatoApliPaciente = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPopupMenuCopiarPegar = new javax.swing.JPopupMenu();
        jMenuItemCopiar = new javax.swing.JMenuItem();
        jMenuItemPegar = new javax.swing.JMenuItem();
        jToolBarProductos = new javax.swing.JToolBar();
        jButtonPrimeroEtiquetas = new javax.swing.JButton();
        jButtonAtrasEtiquetas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabelPosicionEtiquetas = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonSiguienteEtiquetas = new javax.swing.JButton();
        jButtonUltimoEtiquetas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonNuevoEtiquetas = new javax.swing.JButton();
        jButtonModificarEtiquetas = new javax.swing.JButton();
        jButtonEliminarEtiquetas = new javax.swing.JButton();
        jButtonImprimirEtiqueta = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelAceptarCancelar = new javax.swing.JPanel();
        jButtonAceptarEtiquetas = new javax.swing.JButton();
        jButtonCancelarEtiquetas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelListaEtiquetas = new javax.swing.JPanel();
        jScrollPaneListaEtiquetas = new javax.swing.JScrollPane();
        jListEtiquetas = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jPanelEdicionDatosEtiquetas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaEtiquetasMedicamento = new javax.swing.JTextArea();
        jLabelIdFichasDeMedicamentos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaEtiquetasUtilizacion = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaEtiquetasConservacion = new javax.swing.JTextArea();
        jTextFieldEtiquetasConcentracion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEtiquetasElaboradoPor = new javax.swing.JComboBox();
        jTextFieldEtiquetasCaducidad = new javax.swing.JTextField();
        jComboBoxEtiquetasTipoEtiqueta = new javax.swing.JComboBox();
        jTextFieldEtiquetasStockMinimo = new javax.swing.JTextField();
        jTextFieldEtiquetasLibroRecetario = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaEtiquetasReferenciaBibliografica = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaEtiquetasReferenciaCaducidad = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMedicamento = new javax.swing.JComboBox();
        jPanelProductosBuscar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxBuscarEtiquetas = new javax.swing.JComboBox();
        jTextFieldBuscarEtiquetas = new javax.swing.JTextField();
        jButtonBuscarEtiquetas = new javax.swing.JButton();
        jButtonQuitarBuscarEtiquetas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemArchivoNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemArchivoSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemEditarModificar = new javax.swing.JMenuItem();
        jMenuItemEditarEliminar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemVerPrimero = new javax.swing.JMenuItem();
        jMenuItemVerAnterior = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVerSiguiente = new javax.swing.JMenuItem();
        jMenuItemVerUltimo = new javax.swing.JMenuItem();

        jDialogImprimirEtiquetas.setAlwaysOnTop(true);
        jDialogImprimirEtiquetas.setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jRadioButtonDialogImprimirTipoA.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoA);
        jRadioButtonDialogImprimirTipoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoA.setText("Pequeño (tipo A)");

        jRadioButtonDialogImprimirTipoC.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoC);
        jRadioButtonDialogImprimirTipoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoC.setText("Grande (tipo C)");

        jRadioButtonDialogImprimirTipoB.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoB);
        jRadioButtonDialogImprimirTipoB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoB.setText("Mediano (tipo B)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tamaño de la etiqueta:");
        jLabel10.setToolTipText("Elige entre uno de los posibles tamaños para las etiquetas");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Fecha de elaboración:");

        jFormattedTextFieldFechaElaboracion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        jFormattedTextFieldFechaElaboracion.setToolTipText("Dejar en blanco si no se quiere poner una fecha concreta");
        jFormattedTextFieldFechaElaboracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDialogImprimirTipoC)
                            .addComponent(jRadioButtonDialogImprimirTipoB)
                            .addComponent(jRadioButtonDialogImprimirTipoA)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jFormattedTextFieldFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldFechaElaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mostrar campos adicionales:");
        jLabel11.setToolTipText("Permite añadir a la etiqueta datos adicionales además de los habituales");

        jCheckBoxDialogImprimirUtilizacion.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxDialogImprimirUtilizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxDialogImprimirUtilizacion.setText("Utilización");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jCheckBoxDialogImprimirUtilizacion)))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxDialogImprimirUtilizacion)
                .addGap(35, 35, 35))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Formato APLI 56");
        jLabel12.setToolTipText("Imprime las etiquetas en una hoja APLI de 56 pegatinas");

        jRadioButtonDialogImprimirFormatoApli.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButtonDialogImprimirFormatoApli);
        jRadioButtonDialogImprimirFormatoApli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirFormatoApli.setText("Sí");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("No");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDialogImprimirFormatoApli)
                            .addComponent(jRadioButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDialogImprimirFormatoApli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonDialogImprimirPreview.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDialogImprimirPreview.setText("Vista preliminar");

        jButtonDialogImprimirVolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDialogImprimirVolver.setText("Volver");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonDialogImprimirPreview)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDialogImprimirVolver)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDialogImprimirPreview)
                    .addComponent(jButtonDialogImprimirVolver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogImprimirEtiquetasLayout = new javax.swing.GroupLayout(jDialogImprimirEtiquetas.getContentPane());
        jDialogImprimirEtiquetas.getContentPane().setLayout(jDialogImprimirEtiquetasLayout);
        jDialogImprimirEtiquetasLayout.setHorizontalGroup(
            jDialogImprimirEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogImprimirEtiquetasLayout.setVerticalGroup(
            jDialogImprimirEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogImprimirEtiquetasPaciente.setAlwaysOnTop(true);
        jDialogImprimirEtiquetasPaciente.setModal(true);

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jRadioButtonDialogImprimirTipoAPaciente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoAPaciente);
        jRadioButtonDialogImprimirTipoAPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoAPaciente.setText("Pequeño (tipo A)");

        jRadioButtonDialogImprimirTipoCPaciente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoCPaciente);
        jRadioButtonDialogImprimirTipoCPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoCPaciente.setText("Grande (tipo C)");

        jRadioButtonDialogImprimirTipoBPaciente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonDialogImprimirTipoBPaciente);
        jRadioButtonDialogImprimirTipoBPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirTipoBPaciente.setText("Mediano (tipo B)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tamaño de la etiqueta:");
        jLabel19.setToolTipText("Elige entre uno de los posibles tamaños para las etiquetas");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Fecha de elaboración:");

        jFormattedTextFieldFechaElaboracionPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yy"))));
        jFormattedTextFieldFechaElaboracionPaciente.setToolTipText("Dejar en blanco si no se quiere poner una fecha concreta");
        jFormattedTextFieldFechaElaboracionPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDialogImprimirTipoCPaciente)
                            .addComponent(jRadioButtonDialogImprimirTipoBPaciente)
                            .addComponent(jRadioButtonDialogImprimirTipoAPaciente)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jFormattedTextFieldFechaElaboracionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoAPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoBPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDialogImprimirTipoCPaciente)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldFechaElaboracionPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Mostrar campos adicionales:");
        jLabel20.setToolTipText("Permite añadir a la etiqueta datos adicionales además de los habituales");

        jCheckBoxDialogImprimirUtilizacionPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxDialogImprimirUtilizacionPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxDialogImprimirUtilizacionPaciente.setText("Utilización");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCheckBoxDialogImprimirUtilizacionPaciente)))
                .addGap(30, 30, 30))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDialogImprimirUtilizacionPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonDialogImprimirPreviewPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDialogImprimirPreviewPaciente.setText("Vista preliminar");

        jButtonDialogImprimirVolverPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDialogImprimirVolverPaciente.setText("Volver");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jCheckBoxNombrePaciente.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxNombrePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBoxNombrePaciente.setText("Especificar datos de paciente");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Nombre y apellidos:");

        jTextFieldNombrePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNombrePaciente.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Número de etiquetas a imprimir:");

        jSpinnerNumeroEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerNumeroEtiquetas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        jSpinnerNumeroEtiquetas.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerNumeroEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxNombrePaciente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxNombrePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jSpinnerNumeroEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Formato APLI 56");
        jLabel25.setToolTipText("Imprime las etiquetas en una hoja APLI de 56 pegatinas");

        jRadioButtonDialogImprimirFormatoApliPaciente.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButtonDialogImprimirFormatoApliPaciente);
        jRadioButtonDialogImprimirFormatoApliPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonDialogImprimirFormatoApliPaciente.setText("Sí");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("No");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDialogImprimirFormatoApliPaciente)
                            .addComponent(jRadioButton3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDialogImprimirFormatoApliPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButtonDialogImprimirPreviewPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDialogImprimirVolverPaciente))
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDialogImprimirPreviewPaciente)
                    .addComponent(jButtonDialogImprimirVolverPaciente))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jDialogImprimirEtiquetasPacienteLayout = new javax.swing.GroupLayout(jDialogImprimirEtiquetasPaciente.getContentPane());
        jDialogImprimirEtiquetasPaciente.getContentPane().setLayout(jDialogImprimirEtiquetasPacienteLayout);
        jDialogImprimirEtiquetasPacienteLayout.setHorizontalGroup(
            jDialogImprimirEtiquetasPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogImprimirEtiquetasPacienteLayout.setVerticalGroup(
            jDialogImprimirEtiquetasPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItemCopiar.setText("Copiar (Ctlr+C)");
        jPopupMenuCopiarPegar.add(jMenuItemCopiar);

        jMenuItemPegar.setText("Pegar (Ctlr+V)");
        jPopupMenuCopiarPegar.add(jMenuItemPegar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farmacotecnia->Etiquetas de medicamentos");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jToolBarProductos.setBackground(new java.awt.Color(255, 221, 174));
        jToolBarProductos.setFloatable(false);
        jToolBarProductos.setRollover(true);

        jButtonPrimeroEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaPrimero.png"))); // NOI18N
        jButtonPrimeroEtiquetas.setToolTipText("Se coloca en la primera etiqueta");
        jButtonPrimeroEtiquetas.setEnabled(false);
        jButtonPrimeroEtiquetas.setFocusable(false);
        jButtonPrimeroEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimeroEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonPrimeroEtiquetas);

        jButtonAtrasEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaIzquierda.png"))); // NOI18N
        jButtonAtrasEtiquetas.setToolTipText("Se coloca en la etiqueta anterior");
        jButtonAtrasEtiquetas.setEnabled(false);
        jButtonAtrasEtiquetas.setFocusable(false);
        jButtonAtrasEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAtrasEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonAtrasEtiquetas);
        jToolBarProductos.add(jSeparator3);

        jLabelPosicionEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPosicionEtiquetas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPosicionEtiquetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPosicionEtiquetas.setText("Producto 200 de 300");
        jLabelPosicionEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBarProductos.add(jLabelPosicionEtiquetas);
        jToolBarProductos.add(jSeparator4);

        jButtonSiguienteEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaDerecha.png"))); // NOI18N
        jButtonSiguienteEtiquetas.setToolTipText("Se coloca en la etiqueta siguiente");
        jButtonSiguienteEtiquetas.setFocusable(false);
        jButtonSiguienteEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguienteEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonSiguienteEtiquetas);

        jButtonUltimoEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/flechaUltimo.png"))); // NOI18N
        jButtonUltimoEtiquetas.setToolTipText("Se coloca en la última etiqueta");
        jButtonUltimoEtiquetas.setFocusable(false);
        jButtonUltimoEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimoEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonUltimoEtiquetas);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator2.setPreferredSize(new java.awt.Dimension(6, 1));
        jToolBarProductos.add(jSeparator2);

        jButtonNuevoEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/nuevaEtiqueta_1.png"))); // NOI18N
        jButtonNuevoEtiquetas.setToolTipText("Crea una nueva etiqueta");
        jButtonNuevoEtiquetas.setFocusable(false);
        jButtonNuevoEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevoEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonNuevoEtiquetas);

        jButtonModificarEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/etiquetaModificar_1.png"))); // NOI18N
        jButtonModificarEtiquetas.setToolTipText("Permite modificar la  etiqueta actual, pulsar los botones de aceptar o cancelar situados al final de la sección datos etiqueta para salir del modo de edición");
        jButtonModificarEtiquetas.setFocusable(false);
        jButtonModificarEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonModificarEtiquetas);

        jButtonEliminarEtiquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/etiquetaBorrar_1.png"))); // NOI18N
        jButtonEliminarEtiquetas.setToolTipText("Elimina la etiqueta actual");
        jButtonEliminarEtiquetas.setFocusable(false);
        jButtonEliminarEtiquetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarEtiquetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonEliminarEtiquetas);

        jButtonImprimirEtiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/sacyl/caza/farmacia/resources/etiquetaImprimirr_1.png"))); // NOI18N
        jButtonImprimirEtiqueta.setToolTipText("Muestra la etiqueta relacionada con este medicamento");
        jButtonImprimirEtiqueta.setFocusable(false);
        jButtonImprimirEtiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImprimirEtiqueta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarProductos.add(jButtonImprimirEtiqueta);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(950, 620));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAceptarCancelar.setBackground(new java.awt.Color(255, 221, 174));

        jButtonAceptarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAceptarEtiquetas.setMnemonic('A');
        jButtonAceptarEtiquetas.setText("Aceptar");

        jButtonCancelarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelarEtiquetas.setMnemonic('C');
        jButtonCancelarEtiquetas.setText("Cancelar");

        javax.swing.GroupLayout jPanelAceptarCancelarLayout = new javax.swing.GroupLayout(jPanelAceptarCancelar);
        jPanelAceptarCancelar.setLayout(jPanelAceptarCancelarLayout);
        jPanelAceptarCancelarLayout.setHorizontalGroup(
            jPanelAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptarCancelarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonAceptarEtiquetas)
                .addGap(39, 39, 39)
                .addComponent(jButtonCancelarEtiquetas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAceptarCancelarLayout.setVerticalGroup(
            jPanelAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAceptarCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAceptarCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptarEtiquetas)
                    .addComponent(jButtonCancelarEtiquetas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanelAceptarCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 529, 280, -1));
        jLayeredPane1.setLayer(jPanelAceptarCancelar, javax.swing.JLayeredPane.DRAG_LAYER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(951, 1265));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(932, 1265));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelListaEtiquetas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaEtiquetas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2), "Lista Medicamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), java.awt.Color.black)); // NOI18N

        jListEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListEtiquetas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneListaEtiquetas.setViewportView(jListEtiquetas);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipo - Medicamento");

        javax.swing.GroupLayout jPanelListaEtiquetasLayout = new javax.swing.GroupLayout(jPanelListaEtiquetas);
        jPanelListaEtiquetas.setLayout(jPanelListaEtiquetasLayout);
        jPanelListaEtiquetasLayout.setHorizontalGroup(
            jPanelListaEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaEtiquetasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelListaEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPaneListaEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelListaEtiquetasLayout.setVerticalGroup(
            jPanelListaEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaEtiquetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneListaEtiquetas, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanelListaEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 77, -1, -1));

        jPanelEdicionDatosEtiquetas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEdicionDatosEtiquetas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2), "Datos etiqueta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanelEdicionDatosEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanelEdicionDatosEtiquetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Id:");
        jPanelEdicionDatosEtiquetas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");
        jLabel3.setToolTipText("Descripción de la fórmula");
        jPanelEdicionDatosEtiquetas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 65, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Caducidad:");
        jLabel6.setToolTipText("Período de caducidad");
        jPanelEdicionDatosEtiquetas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 257, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Utilización:");
        jLabel7.setToolTipText("Uso del preparado");
        jPanelEdicionDatosEtiquetas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 321, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Conservación");
        jLabel8.setToolTipText("Condiciones de conservación");
        jPanelEdicionDatosEtiquetas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 455, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Concentración:");
        jLabel9.setToolTipText("Concentración de la solución en cada ml.");
        jPanelEdicionDatosEtiquetas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 579, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tipo de etiqueta:");
        jLabel13.setToolTipText("Modelo de etiqueta seleccionado");
        jPanelEdicionDatosEtiquetas.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 643, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Stock mínimo:");
        jLabel14.setToolTipText("Stock mínimo recomendado");
        jPanelEdicionDatosEtiquetas.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 707, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nº de libro de recetario:");
        jPanelEdicionDatosEtiquetas.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 1019, -1, -1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaEtiquetasMedicamento.setEditable(false);
        jTextAreaEtiquetasMedicamento.setColumns(20);
        jTextAreaEtiquetasMedicamento.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaEtiquetasMedicamento.setLineWrap(true);
        jTextAreaEtiquetasMedicamento.setRows(2);
        jTextAreaEtiquetasMedicamento.setText("\n");
        jTextAreaEtiquetasMedicamento.setToolTipText("Descripción de la fórmula");
        jTextAreaEtiquetasMedicamento.setWrapStyleWord(true);
        jTextAreaEtiquetasMedicamento.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane4.setViewportView(jTextAreaEtiquetasMedicamento);

        jPanelEdicionDatosEtiquetas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 88, 354, -1));

        jLabelIdFichasDeMedicamentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdFichasDeMedicamentos.setText("jLabel1");
        jPanelEdicionDatosEtiquetas.add(jLabelIdFichasDeMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 30, -1, -1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaEtiquetasUtilizacion.setEditable(false);
        jTextAreaEtiquetasUtilizacion.setColumns(20);
        jTextAreaEtiquetasUtilizacion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaEtiquetasUtilizacion.setLineWrap(true);
        jTextAreaEtiquetasUtilizacion.setRows(3);
        jTextAreaEtiquetasUtilizacion.setToolTipText("Uso del preparado");
        jTextAreaEtiquetasUtilizacion.setWrapStyleWord(true);
        jTextAreaEtiquetasUtilizacion.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane5.setViewportView(jTextAreaEtiquetasUtilizacion);

        jPanelEdicionDatosEtiquetas.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 344, 354, 93));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaEtiquetasConservacion.setEditable(false);
        jTextAreaEtiquetasConservacion.setColumns(20);
        jTextAreaEtiquetasConservacion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaEtiquetasConservacion.setLineWrap(true);
        jTextAreaEtiquetasConservacion.setRows(3);
        jTextAreaEtiquetasConservacion.setToolTipText("Condiciones de conservación");
        jTextAreaEtiquetasConservacion.setWrapStyleWord(true);
        jTextAreaEtiquetasConservacion.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane6.setViewportView(jTextAreaEtiquetasConservacion);

        jPanelEdicionDatosEtiquetas.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 478, 354, -1));

        jTextFieldEtiquetasConcentracion.setEditable(false);
        jTextFieldEtiquetasConcentracion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEtiquetasConcentracion.setText("cuasi preparado oficinal");
        jTextFieldEtiquetasConcentracion.setToolTipText("Concentración de la solución en cada ml.");
        jPanelEdicionDatosEtiquetas.add(jTextFieldEtiquetasConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 602, 364, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Elaborado por:");
        jPanelEdicionDatosEtiquetas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 219, -1, -1));

        jComboBoxEtiquetasElaboradoPor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEtiquetasElaboradoPor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "A", "E", "F" }));
        jComboBoxEtiquetasElaboradoPor.setToolTipText("A= auxiliar, E= enfermero, F= farmaceútico");
        jComboBoxEtiquetasElaboradoPor.setEnabled(false);
        jPanelEdicionDatosEtiquetas.add(jComboBoxEtiquetasElaboradoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 216, 265, -1));

        jTextFieldEtiquetasCaducidad.setEditable(false);
        jTextFieldEtiquetasCaducidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEtiquetasCaducidad.setText("jTextField1");
        jTextFieldEtiquetasCaducidad.setToolTipText("Período de caducidad");
        jPanelEdicionDatosEtiquetas.add(jTextFieldEtiquetasCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 280, 364, -1));

        jComboBoxEtiquetasTipoEtiqueta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEtiquetasTipoEtiqueta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        jComboBoxEtiquetasTipoEtiqueta.setToolTipText("Tamaño preferente de la etiqueta (A=pequeño, B=mediano, C=grande)");
        jComboBoxEtiquetasTipoEtiqueta.setEnabled(false);
        jPanelEdicionDatosEtiquetas.add(jComboBoxEtiquetasTipoEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 666, 364, -1));

        jTextFieldEtiquetasStockMinimo.setEditable(false);
        jTextFieldEtiquetasStockMinimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEtiquetasStockMinimo.setText("cuasi preparado oficinal");
        jTextFieldEtiquetasStockMinimo.setToolTipText("Stock mínimo recomendado");
        jPanelEdicionDatosEtiquetas.add(jTextFieldEtiquetasStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 730, 364, -1));

        jTextFieldEtiquetasLibroRecetario.setEditable(false);
        jTextFieldEtiquetasLibroRecetario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEtiquetasLibroRecetario.setText("cuasi preparado oficinal");
        jPanelEdicionDatosEtiquetas.add(jTextFieldEtiquetasLibroRecetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 1042, 364, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Referencia bibliográfica:");
        jPanelEdicionDatosEtiquetas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 771, -1, -1));

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaEtiquetasReferenciaBibliografica.setEditable(false);
        jTextAreaEtiquetasReferenciaBibliografica.setColumns(20);
        jTextAreaEtiquetasReferenciaBibliografica.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaEtiquetasReferenciaBibliografica.setLineWrap(true);
        jTextAreaEtiquetasReferenciaBibliografica.setRows(3);
        jTextAreaEtiquetasReferenciaBibliografica.setWrapStyleWord(true);
        jTextAreaEtiquetasReferenciaBibliografica.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane7.setViewportView(jTextAreaEtiquetasReferenciaBibliografica);

        jPanelEdicionDatosEtiquetas.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 794, 364, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Referencia caducidad:");
        jPanelEdicionDatosEtiquetas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 895, -1, -1));

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextAreaEtiquetasReferenciaCaducidad.setEditable(false);
        jTextAreaEtiquetasReferenciaCaducidad.setColumns(20);
        jTextAreaEtiquetasReferenciaCaducidad.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaEtiquetasReferenciaCaducidad.setLineWrap(true);
        jTextAreaEtiquetasReferenciaCaducidad.setRows(3);
        jTextAreaEtiquetasReferenciaCaducidad.setWrapStyleWord(true);
        jTextAreaEtiquetasReferenciaCaducidad.setComponentPopupMenu(jPopupMenuCopiarPegar);
        jScrollPane8.setViewportView(jTextAreaEtiquetasReferenciaCaducidad);

        jPanelEdicionDatosEtiquetas.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 918, 364, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Medicamento:");
        jPanelEdicionDatosEtiquetas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 152, -1, -1));

        jComboBoxMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMedicamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMedicamento.setToolTipText("Nombre del medicamento con el que está relacionado");
        jComboBoxMedicamento.setEnabled(false);
        jPanelEdicionDatosEtiquetas.add(jComboBoxMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 175, 364, -1));

        jPanel1.add(jPanelEdicionDatosEtiquetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 77, 450, 1090));

        jPanelProductosBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Buscar por:");

        jComboBoxBuscarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBuscarEtiquetas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descripción", "Tipo de etiqueta" }));
        jComboBoxBuscarEtiquetas.setToolTipText("Seleccionar por que criterio buscar");

        jTextFieldBuscarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscarEtiquetas.setToolTipText("Introducir el texto de guia para buscar");

        jButtonBuscarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarEtiquetas.setMnemonic('B');
        jButtonBuscarEtiquetas.setText("Buscar");
        jButtonBuscarEtiquetas.setToolTipText("Buscar etiquetas que coincidan con los criterios elegidos");

        jButtonQuitarBuscarEtiquetas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonQuitarBuscarEtiquetas.setMnemonic('Q');
        jButtonQuitarBuscarEtiquetas.setText("Quitar búsqueda");
        jButtonQuitarBuscarEtiquetas.setToolTipText("Volver a mostrar todas las etiquetas");

        javax.swing.GroupLayout jPanelProductosBuscarLayout = new javax.swing.GroupLayout(jPanelProductosBuscar);
        jPanelProductosBuscar.setLayout(jPanelProductosBuscarLayout);
        jPanelProductosBuscarLayout.setHorizontalGroup(
            jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitarBuscarEtiquetas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProductosBuscarLayout.setVerticalGroup(
            jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProductosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jComboBoxBuscarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBuscarEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarEtiquetas)
                    .addComponent(jButtonQuitarBuscarEtiquetas))
                .addContainerGap())
        );

        jPanel1.add(jPanelProductosBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, 871, -1));

        jScrollPane1.setViewportView(jPanel1);

        jLayeredPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 950, 640));

        jMenu1.setText("Archivo");

        jMenuItemArchivoNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemArchivoNuevo.setText("Nuevo");
        jMenu1.add(jMenuItemArchivoNuevo);
        jMenu1.add(jSeparator1);

        jMenuItemArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemArchivoSalir.setText("Salir");
        jMenu1.add(jMenuItemArchivoSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItemEditarModificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarModificar.setText("Modificar");
        jMenu2.add(jMenuItemEditarModificar);

        jMenuItemEditarEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarEliminar.setText("Eliminar");
        jMenu2.add(jMenuItemEditarEliminar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");

        jMenuItemVerPrimero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerPrimero.setText("Primero");
        jMenu3.add(jMenuItemVerPrimero);

        jMenuItemVerAnterior.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerAnterior.setText("Anterior");
        jMenu3.add(jMenuItemVerAnterior);
        jMenu3.add(jSeparator14);

        jMenuItemVerSiguiente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerSiguiente.setText("Siguiente");
        jMenu3.add(jMenuItemVerSiguiente);

        jMenuItemVerUltimo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVerUltimo.setText("Último");
        jMenu3.add(jMenuItemVerUltimo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(getClass().getResource("/es/sacyl/caza/farmacia/resources/images.jpg"));

        
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEtiquetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaEtiquetas dialog = new VentanaEtiquetas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JButton jButtonAceptarEtiquetas;
    public javax.swing.JButton jButtonAtrasEtiquetas;
    public javax.swing.JButton jButtonBuscarEtiquetas;
    public javax.swing.JButton jButtonCancelarEtiquetas;
    public javax.swing.JButton jButtonDialogImprimirPreview;
    public javax.swing.JButton jButtonDialogImprimirPreviewPaciente;
    public javax.swing.JButton jButtonDialogImprimirVolver;
    public javax.swing.JButton jButtonDialogImprimirVolverPaciente;
    public javax.swing.JButton jButtonEliminarEtiquetas;
    public javax.swing.JButton jButtonImprimirEtiqueta;
    public javax.swing.JButton jButtonModificarEtiquetas;
    public javax.swing.JButton jButtonNuevoEtiquetas;
    public javax.swing.JButton jButtonPrimeroEtiquetas;
    public javax.swing.JButton jButtonQuitarBuscarEtiquetas;
    public javax.swing.JButton jButtonSiguienteEtiquetas;
    public javax.swing.JButton jButtonUltimoEtiquetas;
    public javax.swing.JCheckBox jCheckBoxDialogImprimirUtilizacion;
    public javax.swing.JCheckBox jCheckBoxDialogImprimirUtilizacionPaciente;
    public javax.swing.JCheckBox jCheckBoxNombrePaciente;
    public javax.swing.JComboBox jComboBoxBuscarEtiquetas;
    public javax.swing.JComboBox jComboBoxEtiquetasElaboradoPor;
    public javax.swing.JComboBox jComboBoxEtiquetasTipoEtiqueta;
    public javax.swing.JComboBox jComboBoxMedicamento;
    public javax.swing.JDialog jDialogImprimirEtiquetas;
    public javax.swing.JDialog jDialogImprimirEtiquetasPaciente;
    public javax.swing.JFormattedTextField jFormattedTextFieldFechaElaboracion;
    public javax.swing.JFormattedTextField jFormattedTextFieldFechaElaboracionPaciente;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelIdFichasDeMedicamentos;
    public javax.swing.JLabel jLabelPosicionEtiquetas;
    public javax.swing.JLayeredPane jLayeredPane1;
    public javax.swing.JList jListEtiquetas;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemArchivoNuevo;
    public javax.swing.JMenuItem jMenuItemArchivoSalir;
    public javax.swing.JMenuItem jMenuItemCopiar;
    public javax.swing.JMenuItem jMenuItemEditarEliminar;
    public javax.swing.JMenuItem jMenuItemEditarModificar;
    public javax.swing.JMenuItem jMenuItemPegar;
    public javax.swing.JMenuItem jMenuItemVerAnterior;
    public javax.swing.JMenuItem jMenuItemVerPrimero;
    public javax.swing.JMenuItem jMenuItemVerSiguiente;
    public javax.swing.JMenuItem jMenuItemVerUltimo;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JPanel jPanelAceptarCancelar;
    public javax.swing.JPanel jPanelEdicionDatosEtiquetas;
    public javax.swing.JPanel jPanelListaEtiquetas;
    public javax.swing.JPanel jPanelProductosBuscar;
    public javax.swing.JPopupMenu jPopupMenuCopiarPegar;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirFormatoApli;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirFormatoApliPaciente;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoA;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoAPaciente;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoB;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoBPaciente;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoC;
    public javax.swing.JRadioButton jRadioButtonDialogImprimirTipoCPaciente;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPaneListaEtiquetas;
    public javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JPopupMenu.Separator jSeparator14;
    public javax.swing.JToolBar.Separator jSeparator2;
    public javax.swing.JToolBar.Separator jSeparator3;
    public javax.swing.JToolBar.Separator jSeparator4;
    public javax.swing.JSpinner jSpinnerNumeroEtiquetas;
    public javax.swing.JTextArea jTextAreaEtiquetasConservacion;
    public javax.swing.JTextArea jTextAreaEtiquetasMedicamento;
    public javax.swing.JTextArea jTextAreaEtiquetasReferenciaBibliografica;
    public javax.swing.JTextArea jTextAreaEtiquetasReferenciaCaducidad;
    public javax.swing.JTextArea jTextAreaEtiquetasUtilizacion;
    public javax.swing.JTextField jTextFieldBuscarEtiquetas;
    public javax.swing.JTextField jTextFieldEtiquetasCaducidad;
    public javax.swing.JTextField jTextFieldEtiquetasConcentracion;
    public javax.swing.JTextField jTextFieldEtiquetasLibroRecetario;
    public javax.swing.JTextField jTextFieldEtiquetasStockMinimo;
    public javax.swing.JTextField jTextFieldNombrePaciente;
    public javax.swing.JToolBar jToolBarProductos;
    // End of variables declaration//GEN-END:variables
}
