package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA



/**
 * Etiquetas generated by hbm2java
 */
public class Etiquetas  implements java.io.Serializable {


     private Integer idEtiqueta;
     private FichasDeMedicamentos fichasDeMedicamentos;
     private String descripcion;
     private String quienLoElabora;
     private String caducidad;
     private String utilizacion;
     private String conservacion;
     private String concentracion;
     private String tipoEtiqueta;
     private String stockMinimo;
     private String referenciaBiblio;
     private String referenciaCaducidad;
     private String tipo;
     private String composicion;
     private String EDO;
     private String viaDeAdmon;
     private Integer numLibroRecetario;
     private String fechaDeElaboracion;
     private String prescriptor;
     private String nombreDelPaciente;
     private String servicio;
     private String advertencia;

    public Etiquetas() {
    }

    public Etiquetas(FichasDeMedicamentos fichasDeMedicamentos, String descripcion, String quienLoElabora, String caducidad, String utilizacion, String conservacion, String concentracion, String tipoEtiqueta, String stockMinimo, String referenciaBiblio, String referenciaCaducidad, String tipo, String composicion, String EDO, String viaDeAdmon, Integer numLibroRecetario, String fechaDeElaboracion, String prescriptor, String nombreDelPaciente, String servicio, String advertencia) {
       this.fichasDeMedicamentos = fichasDeMedicamentos;
       this.descripcion = descripcion;
       this.quienLoElabora = quienLoElabora;
       this.caducidad = caducidad;
       this.utilizacion = utilizacion;
       this.conservacion = conservacion;
       this.concentracion = concentracion;
       this.tipoEtiqueta = tipoEtiqueta;
       this.stockMinimo = stockMinimo;
       this.referenciaBiblio = referenciaBiblio;
       this.referenciaCaducidad = referenciaCaducidad;
       this.tipo = tipo;
       this.composicion = composicion;
       this.EDO = EDO;
       this.viaDeAdmon = viaDeAdmon;
       this.numLibroRecetario = numLibroRecetario;
       this.fechaDeElaboracion = fechaDeElaboracion;
       this.prescriptor = prescriptor;
       this.nombreDelPaciente = nombreDelPaciente;
       this.servicio = servicio;
       this.advertencia = advertencia;
    }
   
    public Integer getIdEtiqueta() {
        return this.idEtiqueta;
    }
    
    public void setIdEtiqueta(Integer idEtiqueta) {
        this.idEtiqueta = idEtiqueta;
    }
    public FichasDeMedicamentos getFichasDeMedicamentos() {
        return this.fichasDeMedicamentos;
    }
    
    public void setFichasDeMedicamentos(FichasDeMedicamentos fichasDeMedicamentos) {
        this.fichasDeMedicamentos = fichasDeMedicamentos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getQuienLoElabora() {
        return this.quienLoElabora;
    }
    
    public void setQuienLoElabora(String quienLoElabora) {
        this.quienLoElabora = quienLoElabora;
    }
    public String getCaducidad() {
        return this.caducidad;
    }
    
    public void setCaducidad(String caducidad) {
        this.caducidad = caducidad;
    }
    public String getUtilizacion() {
        return this.utilizacion;
    }
    
    public void setUtilizacion(String utilizacion) {
        this.utilizacion = utilizacion;
    }
    public String getConservacion() {
        return this.conservacion;
    }
    
    public void setConservacion(String conservacion) {
        this.conservacion = conservacion;
    }
    public String getConcentracion() {
        return this.concentracion;
    }
    
    public void setConcentracion(String concentracion) {
        this.concentracion = concentracion;
    }
    public String getTipoEtiqueta() {
        return this.tipoEtiqueta;
    }
    
    public void setTipoEtiqueta(String tipoEtiqueta) {
        this.tipoEtiqueta = tipoEtiqueta;
    }
    public String getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(String stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public String getReferenciaBiblio() {
        return this.referenciaBiblio;
    }
    
    public void setReferenciaBiblio(String referenciaBiblio) {
        this.referenciaBiblio = referenciaBiblio;
    }
    public String getReferenciaCaducidad() {
        return this.referenciaCaducidad;
    }
    
    public void setReferenciaCaducidad(String referenciaCaducidad) {
        this.referenciaCaducidad = referenciaCaducidad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getComposicion() {
        return this.composicion;
    }
    
    public void setComposicion(String composicion) {
        this.composicion = composicion;
    }
    public String getEDO() {
        return this.EDO;
    }
    
    public void setEDO(String EDO) {
        this.EDO = EDO;
    }
    public String getViaDeAdmon() {
        return this.viaDeAdmon;
    }
    
    public void setViaDeAdmon(String viaDeAdmon) {
        this.viaDeAdmon = viaDeAdmon;
    }
    public Integer getNumLibroRecetario() {
        return this.numLibroRecetario;
    }
    
    public void setNumLibroRecetario(Integer numLibroRecetario) {
        this.numLibroRecetario = numLibroRecetario;
    }
    public String getFechaDeElaboracion() {
        return this.fechaDeElaboracion;
    }
    
    public void setFechaDeElaboracion(String fechaDeElaboracion) {
        this.fechaDeElaboracion = fechaDeElaboracion;
    }
    public String getPrescriptor() {
        return this.prescriptor;
    }
    
    public void setPrescriptor(String prescriptor) {
        this.prescriptor = prescriptor;
    }
    public String getNombreDelPaciente() {
        return this.nombreDelPaciente;
    }
    
    public void setNombreDelPaciente(String nombreDelPaciente) {
        this.nombreDelPaciente = nombreDelPaciente;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }
    public String getAdvertencia() {
        return this.advertencia;
    }
    
    public void setAdvertencia(String advertencia) {
        this.advertencia = advertencia;
    }




}


