package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FichasDeMedicamentos generated by hbm2java
 */
public class FichasDeMedicamentos  implements java.io.Serializable {


     private Integer idMedicamento;
     private String medicamento;
     private String elaboradoPor;
     private String procedimiento;
     private String observaciones;
     private String estabilidad;
     private String organolepsisDatos;
     private String viaDeAdmon;
     private String paraEtiqueta;
     private String origen;
     private Integer veredicto;
     private String veredObservac;
     private String observacParaElaboracion;
     private String tipo;
     private String algunEdo;
     private Set materialParaElaborarUnions = new HashSet(0);
     private Set materialDeEnvasadoUnions = new HashSet(0);
     private Set etiquetases = new HashSet(0);
     private Set maquinariaUnions = new HashSet(0);
     private Set productosUnions = new HashSet(0);

    public FichasDeMedicamentos() {
    }

    public FichasDeMedicamentos(String medicamento, String elaboradoPor, String procedimiento, String observaciones, String estabilidad, String organolepsisDatos, String viaDeAdmon, String paraEtiqueta, String origen, Integer veredicto, String veredObservac, String observacParaElaboracion, String tipo, String algunEdo, Set materialParaElaborarUnions, Set materialDeEnvasadoUnions, Set etiquetases, Set maquinariaUnions, Set productosUnions) {
       this.medicamento = medicamento;
       this.elaboradoPor = elaboradoPor;
       this.procedimiento = procedimiento;
       this.observaciones = observaciones;
       this.estabilidad = estabilidad;
       this.organolepsisDatos = organolepsisDatos;
       this.viaDeAdmon = viaDeAdmon;
       this.paraEtiqueta = paraEtiqueta;
       this.origen = origen;
       this.veredicto = veredicto;
       this.veredObservac = veredObservac;
       this.observacParaElaboracion = observacParaElaboracion;
       this.tipo = tipo;
       this.algunEdo = algunEdo;
       this.materialParaElaborarUnions = materialParaElaborarUnions;
       this.materialDeEnvasadoUnions = materialDeEnvasadoUnions;
       this.etiquetases = etiquetases;
       this.maquinariaUnions = maquinariaUnions;
       this.productosUnions = productosUnions;
    }
   
    public Integer getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(Integer idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }
    public String getElaboradoPor() {
        return this.elaboradoPor;
    }
    
    public void setElaboradoPor(String elaboradoPor) {
        this.elaboradoPor = elaboradoPor;
    }
    public String getProcedimiento() {
        return this.procedimiento;
    }
    
    public void setProcedimiento(String procedimiento) {
        this.procedimiento = procedimiento;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstabilidad() {
        return this.estabilidad;
    }
    
    public void setEstabilidad(String estabilidad) {
        this.estabilidad = estabilidad;
    }
    public String getOrganolepsisDatos() {
        return this.organolepsisDatos;
    }
    
    public void setOrganolepsisDatos(String organolepsisDatos) {
        this.organolepsisDatos = organolepsisDatos;
    }
    public String getViaDeAdmon() {
        return this.viaDeAdmon;
    }
    
    public void setViaDeAdmon(String viaDeAdmon) {
        this.viaDeAdmon = viaDeAdmon;
    }
    public String getParaEtiqueta() {
        return this.paraEtiqueta;
    }
    
    public void setParaEtiqueta(String paraEtiqueta) {
        this.paraEtiqueta = paraEtiqueta;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public Integer getVeredicto() {
        return this.veredicto;
    }
    
    public void setVeredicto(Integer veredicto) {
        this.veredicto = veredicto;
    }
    public String getVeredObservac() {
        return this.veredObservac;
    }
    
    public void setVeredObservac(String veredObservac) {
        this.veredObservac = veredObservac;
    }
    public String getObservacParaElaboracion() {
        return this.observacParaElaboracion;
    }
    
    public void setObservacParaElaboracion(String observacParaElaboracion) {
        this.observacParaElaboracion = observacParaElaboracion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getAlgunEdo() {
        return this.algunEdo;
    }
    
    public void setAlgunEdo(String algunEdo) {
        this.algunEdo = algunEdo;
    }
    public Set getMaterialParaElaborarUnions() {
        return this.materialParaElaborarUnions;
    }
    
    public void setMaterialParaElaborarUnions(Set materialParaElaborarUnions) {
        this.materialParaElaborarUnions = materialParaElaborarUnions;
    }
    public Set getMaterialDeEnvasadoUnions() {
        return this.materialDeEnvasadoUnions;
    }
    
    public void setMaterialDeEnvasadoUnions(Set materialDeEnvasadoUnions) {
        this.materialDeEnvasadoUnions = materialDeEnvasadoUnions;
    }
    public Set getEtiquetases() {
        return this.etiquetases;
    }
    
    public void setEtiquetases(Set etiquetases) {
        this.etiquetases = etiquetases;
    }
    public Set getMaquinariaUnions() {
        return this.maquinariaUnions;
    }
    
    public void setMaquinariaUnions(Set maquinariaUnions) {
        this.maquinariaUnions = maquinariaUnions;
    }
    public Set getProductosUnions() {
        return this.productosUnions;
    }
    
    public void setProductosUnions(Set productosUnions) {
        this.productosUnions = productosUnions;
    }




}


