package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA



/**
 * MaquinariaUnion generated by hbm2java
 */
public class MaquinariaUnion  implements java.io.Serializable {


     private Integer idMaquinariaUnion;
     private Maquinaria maquinaria;
     private FichasDeMedicamentos fichasDeMedicamentos;

    public MaquinariaUnion() {
    }

    public MaquinariaUnion(Maquinaria maquinaria, FichasDeMedicamentos fichasDeMedicamentos) {
       this.maquinaria = maquinaria;
       this.fichasDeMedicamentos = fichasDeMedicamentos;
    }
   
    public Integer getIdMaquinariaUnion() {
        return this.idMaquinariaUnion;
    }
    
    public void setIdMaquinariaUnion(Integer idMaquinariaUnion) {
        this.idMaquinariaUnion = idMaquinariaUnion;
    }
    public Maquinaria getMaquinaria() {
        return this.maquinaria;
    }
    
    public void setMaquinaria(Maquinaria maquinaria) {
        this.maquinaria = maquinaria;
    }
    public FichasDeMedicamentos getFichasDeMedicamentos() {
        return this.fichasDeMedicamentos;
    }
    
    public void setFichasDeMedicamentos(FichasDeMedicamentos fichasDeMedicamentos) {
        this.fichasDeMedicamentos = fichasDeMedicamentos;
    }




}


