package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Maquinaria generated by hbm2java
 */
public class Maquinaria  implements java.io.Serializable {


     private Integer idMaquinaria;
     private String maquinaria;
     private boolean tenemos;
     private Set maquinariaUnions = new HashSet(0);

    public Maquinaria() {
    }

	
    public Maquinaria(boolean tenemos) {
        this.tenemos = tenemos;
    }
    public Maquinaria(String maquinaria, boolean tenemos, Set maquinariaUnions) {
       this.maquinaria = maquinaria;
       this.tenemos = tenemos;
       this.maquinariaUnions = maquinariaUnions;
    }
   
    public Integer getIdMaquinaria() {
        return this.idMaquinaria;
    }
    
    public void setIdMaquinaria(Integer idMaquinaria) {
        this.idMaquinaria = idMaquinaria;
    }
    public String getMaquinaria() {
        return this.maquinaria;
    }
    
    public void setMaquinaria(String maquinaria) {
        this.maquinaria = maquinaria;
    }
    public boolean isTenemos() {
        return this.tenemos;
    }
    
    public void setTenemos(boolean tenemos) {
        this.tenemos = tenemos;
    }
    public Set getMaquinariaUnions() {
        return this.maquinariaUnions;
    }
    
    public void setMaquinariaUnions(Set maquinariaUnions) {
        this.maquinariaUnions = maquinariaUnions;
    }




}


