package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MaterialParaElaborar generated by hbm2java
 */
public class MaterialParaElaborar  implements java.io.Serializable {


     private Integer idMaterial;
     private String material;
     private boolean tenemos;
     private Set materialParaElaborarUnions = new HashSet(0);

    public MaterialParaElaborar() {
    }

	
    public MaterialParaElaborar(String material, boolean tenemos) {
        this.material = material;
        this.tenemos = tenemos;
    }
    public MaterialParaElaborar(String material, boolean tenemos, Set materialParaElaborarUnions) {
       this.material = material;
       this.tenemos = tenemos;
       this.materialParaElaborarUnions = materialParaElaborarUnions;
    }
   
    public Integer getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(Integer idMaterial) {
        this.idMaterial = idMaterial;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public boolean isTenemos() {
        return this.tenemos;
    }
    
    public void setTenemos(boolean tenemos) {
        this.tenemos = tenemos;
    }
    public Set getMaterialParaElaborarUnions() {
        return this.materialParaElaborarUnions;
    }
    
    public void setMaterialParaElaborarUnions(Set materialParaElaborarUnions) {
        this.materialParaElaborarUnions = materialParaElaborarUnions;
    }




}


