package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MaterialDeEnvasado generated by hbm2java
 */
public class MaterialDeEnvasado  implements java.io.Serializable {


     private Integer idParaEnvasar;
     private String paraEnvasar;
     private boolean tenemos;
     private Set materialDeEnvasadoUnions = new HashSet(0);

    public MaterialDeEnvasado() {
    }

	
    public MaterialDeEnvasado(String paraEnvasar, boolean tenemos) {
        this.paraEnvasar = paraEnvasar;
        this.tenemos = tenemos;
    }
    public MaterialDeEnvasado(String paraEnvasar, boolean tenemos, Set materialDeEnvasadoUnions) {
       this.paraEnvasar = paraEnvasar;
       this.tenemos = tenemos;
       this.materialDeEnvasadoUnions = materialDeEnvasadoUnions;
    }
   
    public Integer getIdParaEnvasar() {
        return this.idParaEnvasar;
    }
    
    public void setIdParaEnvasar(Integer idParaEnvasar) {
        this.idParaEnvasar = idParaEnvasar;
    }
    public String getParaEnvasar() {
        return this.paraEnvasar;
    }
    
    public void setParaEnvasar(String paraEnvasar) {
        this.paraEnvasar = paraEnvasar;
    }
    public boolean isTenemos() {
        return this.tenemos;
    }
    
    public void setTenemos(boolean tenemos) {
        this.tenemos = tenemos;
    }
    public Set getMaterialDeEnvasadoUnions() {
        return this.materialDeEnvasadoUnions;
    }
    
    public void setMaterialDeEnvasadoUnions(Set materialDeEnvasadoUnions) {
        this.materialDeEnvasadoUnions = materialDeEnvasadoUnions;
    }




}


