package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA



/**
 * MaterialParaElaborarUnion generated by hbm2java
 */
public class MaterialParaElaborarUnion  implements java.io.Serializable {


     private Integer idMaterialUnion;
     private MaterialParaElaborar materialParaElaborar;
     private FichasDeMedicamentos fichasDeMedicamentos;

    public MaterialParaElaborarUnion() {
    }

    public MaterialParaElaborarUnion(MaterialParaElaborar materialParaElaborar, FichasDeMedicamentos fichasDeMedicamentos) {
       this.materialParaElaborar = materialParaElaborar;
       this.fichasDeMedicamentos = fichasDeMedicamentos;
    }
   
    public Integer getIdMaterialUnion() {
        return this.idMaterialUnion;
    }
    
    public void setIdMaterialUnion(Integer idMaterialUnion) {
        this.idMaterialUnion = idMaterialUnion;
    }
    public MaterialParaElaborar getMaterialParaElaborar() {
        return this.materialParaElaborar;
    }
    
    public void setMaterialParaElaborar(MaterialParaElaborar materialParaElaborar) {
        this.materialParaElaborar = materialParaElaborar;
    }
    public FichasDeMedicamentos getFichasDeMedicamentos() {
        return this.fichasDeMedicamentos;
    }
    
    public void setFichasDeMedicamentos(FichasDeMedicamentos fichasDeMedicamentos) {
        this.fichasDeMedicamentos = fichasDeMedicamentos;
    }




}


