package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA



/**
 * MaterialDeEnvasadoUnion generated by hbm2java
 */
public class MaterialDeEnvasadoUnion  implements java.io.Serializable {


     private Integer idParaEnvasarUnion;
     private MaterialDeEnvasado materialDeEnvasado;
     private FichasDeMedicamentos fichasDeMedicamentos;

    public MaterialDeEnvasadoUnion() {
    }

    public MaterialDeEnvasadoUnion(MaterialDeEnvasado materialDeEnvasado, FichasDeMedicamentos fichasDeMedicamentos) {
       this.materialDeEnvasado = materialDeEnvasado;
       this.fichasDeMedicamentos = fichasDeMedicamentos;
    }
   
    public Integer getIdParaEnvasarUnion() {
        return this.idParaEnvasarUnion;
    }
    
    public void setIdParaEnvasarUnion(Integer idParaEnvasarUnion) {
        this.idParaEnvasarUnion = idParaEnvasarUnion;
    }
    public MaterialDeEnvasado getMaterialDeEnvasado() {
        return this.materialDeEnvasado;
    }
    
    public void setMaterialDeEnvasado(MaterialDeEnvasado materialDeEnvasado) {
        this.materialDeEnvasado = materialDeEnvasado;
    }
    public FichasDeMedicamentos getFichasDeMedicamentos() {
        return this.fichasDeMedicamentos;
    }
    
    public void setFichasDeMedicamentos(FichasDeMedicamentos fichasDeMedicamentos) {
        this.fichasDeMedicamentos = fichasDeMedicamentos;
    }




}


