package es.sacyl.caza.farmacia.modelo.clases;
// Generated 30-abr-2014 13:00:04 by Hibernate Tools 3.2.1.GA



/**
 * ProductosUnion generated by hbm2java
 */
public class ProductosUnion  implements java.io.Serializable {


     private Integer idComponenteUnion;
     private Productos productos;
     private FichasDeMedicamentos fichasDeMedicamentos;
     private String cantidad;
     private String unidades;
     private String orden;

    public ProductosUnion() {
    }

	
    public ProductosUnion(Productos productos) {
        this.productos = productos;
    }
    public ProductosUnion(Productos productos, FichasDeMedicamentos fichasDeMedicamentos, String cantidad, String unidades, String orden) {
       this.productos = productos;
       this.fichasDeMedicamentos = fichasDeMedicamentos;
       this.cantidad = cantidad;
       this.unidades = unidades;
       this.orden = orden;
    }
   
    public Integer getIdComponenteUnion() {
        return this.idComponenteUnion;
    }
    
    public void setIdComponenteUnion(Integer idComponenteUnion) {
        this.idComponenteUnion = idComponenteUnion;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public FichasDeMedicamentos getFichasDeMedicamentos() {
        return this.fichasDeMedicamentos;
    }
    
    public void setFichasDeMedicamentos(FichasDeMedicamentos fichasDeMedicamentos) {
        this.fichasDeMedicamentos = fichasDeMedicamentos;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(String unidades) {
        this.unidades = unidades;
    }
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }




}


